### ISSUE TITLE
Logged in Session last only a few hours

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#100]
Lychee3 Logged in Sessions last forever, Laravel just for some hours.

**Comment by kamil4** [comment]
Worse, you get a cryptic "Server API error" or something message. Since I tend to mess with server APIs when coding, I'm never initially sure if it's the timeout or if I introduced a new bug...

**Comment by ildyria** [comment]
It is "user settable"

in `.env.example` : https://github.com/LycheeOrg/Lychee-Laravel/blob/master/.env.example#L24
```php
SESSION_LIFETIME=120
```

in `config/session.php` : https://github.com/LycheeOrg/Lychee-Laravel/blob/master/config/session.php
```php
    /*
    |--------------------------------------------------------------------------
    | Session Lifetime
    |--------------------------------------------------------------------------
    |
    | Here you may specify the number of minutes that you wish the session
    | to be allowed to remain idle before it expires. If you want them
    | to immediately expire on the browser closing, set that option.
    |
    */
    'lifetime' => env('SESSION_LIFETIME', 120),
    'expire_on_close' => false,
```

May require documentation, if someone want to add this to the wiki.

**Comment by kamil4** [comment]
I think the cryptic error message the user gets after the session times out _is_ an issue though. Do you think it would be hard to catch it and display a neat "Session timed out" kind of information to the user?

**Comment by SerenaButler** [comment]
I never got a cryptic message though. I were just logged out.

**Comment by SerenaButler** [comment]
There are situations "loosing" the session while in an non-public area. Reloading the page can then result in an empty page or /indeed) in a cryptic message. If session is gone reloading a non public page should refer to the next higher public page.

**Comment by ildyria** [comment]
that should be handled by Lychee-front.

**Comment by SerenaButler** [comment]
Ok :-)

**Comment by kamil4** [comment]
I had a look at it last night. After the session times out, the next request from the front end results in the following error in laravel.log:
```
local.ERROR: The payload is invalid. {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /home/kamil/public_html/tmp/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:195)
```
Followed by a stacktrace 51 frames deep...

I was able to catch it in the front end by testing in the AJAX error handler for `jqXHR.responseJSON.exception === 'Illuminate\\Contracts\\Encryption\\DecryptException'` and redirect the browser to the front page, but it's not a magic bullet. First, it only works with `APP_DEBUG=true` in `.env` -- if it's set to `false` (as it should be in a production installation, right?), all we get in `jqXHR.responseJSON` is `message: "Server Error"`. And second, having that error in the Laravel log every time a session times out feels wrong.

Is there any way for our code on the server side to catch this condition early and reliably send some fixed "timed out" response, with or without `APP_DEBUG`, and without filling the Laravel log with stack traces? I have zero understanding of the inner workings of Laravel, and basically all of those stack frames were in Laravel code and not in ours...

**Comment by d7415** [comment]
> Is there any way for our code on the server side to catch this condition early and reliably send some fixed "timed out" response, with or without `APP_DEBUG`, and without filling the Laravel log with stack traces? I have zero understanding of the inner workings of Laravel, and basically all of those stack frames were in Laravel code and not in ours...

That makes sense to me. Effectively catch "access denied" type errors. I guess we'd need to find out what we're doing (if anything) to trigger this and handle it there. If Laravel's raising the exception before Lychee gets involved, that could be more complicated. There must be some solution though - we can't be the first to have this problem!

**Comment by kamil4** [comment]
I searched the web for `Illuminate\\Contracts\\Encryption\\DecryptException` the other day and found surprisingly little, which makes me think that we must be doing something unique in Lychee to trigger that particular error. @d7415 yeah I too wondered how other Laravel apps handle this. Does Laravel come bundled with some trivial demo app perhaps that one could experiment with to see how it reacts to timeouts?

**Comment by kamil4** [comment]
OK, I submitted PRs that should fix this.

As an aside, experiments I ran seem to indicate that the problem may be due to the prevalent use of POST rather than GET in Lychee. I.e., I was unable to reproduce this problem with `/api/Photo::getArchive`, which is a GET (it just works, even after the session timeout), while POSTs trigger the error, forcing us to reload.

**Comment by kamil4** [comment]
This should now be fixed.
