### ISSUE TITLE
Album view Problem when getting back form a single image that got reloaded via F5

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#101]
Go into Album, click on Image, in Image view do a Browser reload, go back to Album view.

![image](https://user-images.githubusercontent.com/35893306/53639829-9d7cb700-3c2a-11e9-9eef-b8a46ea78594.png)

Check here too for screencast: https://drive.google.com/file/d/1bJfnfdn7eZNj5LNvgm6jEi-U662kTErZ/view?usp=drivesdk

**Comment by kamil4** [comment]
Yikes, that's ugly! It's even worse with the unjustified layout, where the pictures disappear completely. I'm not sure if I'm responsible for this bug but since I've been messing around that part of the code lately, I'll have a look this weekend.
Thanks for the report!
