### ISSUE TITLE
No Pinch to Zoom in and out on mobile (iPhone)

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#105]
iPhone X, actual iOS, No Pinch to Zoom in and out in image view.

**Comment by SerenaButler** [comment]
Modify /resources/views/includes/head.blade.php with:

From:

`<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0">`

To:

`<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=4.0", user-scalable=yes">`

**Comment by ildyria** [comment]
Can you make a PR for that to Lychee-front ?

**Comment by SerenaButler** [comment]
Done :-)
