### ISSUE TITLE
Hidpi is breaking the *.svg's ... because x2 not defined.

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#107]
![image](https://user-images.githubusercontent.com/35893306/53681997-8d7bda80-3cf1-11e9-8bc7-531b60111e07.png)

![image](https://user-images.githubusercontent.com/35893306/53682003-aa181280-3cf1-11e9-9c2b-9fdf62039962.png)

srcset="undefined 2x"  needs to be remove though :-)

**Comment by kamil4** [comment]
This is embarrassing :frowning_face: - how did I miss that? Anyway, should be fixed now.
@ildyria feel free to assign such bugs to me in the future so that they get resolved in a more timely manner. I was preoccupied with my improved-videos work.
