### ISSUE TITLE
Image title truncated.

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#109]
Is there any reason for:

.content .album .overlay h1, .content .photo .overlay h1 {
    **overflow: hidden;**
}

truncating the image title?

![image](https://user-images.githubusercontent.com/35893306/53695296-deef9c80-3db9-11e9-86e9-7ddec5060da4.png)

**Comment by kamil4** [comment]
This is inherited from the square layout which, internally, is Lychee's default (even if it's not exposed to the user as such). Anyway, I think I can fix it in CSS...

**Comment by SerenaButler** [comment]
div.justified-layout div.photo div.overlay h1 {
    overflow: visible;
}
