### ISSUE TITLE
Download original image - only recompressed copy available?

### ISSUE THREAD

**Issue by ABLomas** [LycheeOrg/Lychee-Laravel#111]
In Lychee 3 it was possible to get link to original image, stored on server. No visual differences, size is identical.
Testing Lychee-Laravel now and it seems that we can't get original image anymore.
Test1:
 - upload any image (i used 2048 x 1152  Pixels, 1.52 MB (1.592.868 Bytes)) image
 - get link to image using three dots => "Full Photo"
 - save image to disk

Result: 2048 x 1152  Pixels, **2.83 MB (2.965.819 Bytes)** image (almost twice as big).

 Another test using three dots => Download.
Result:
```
(1/1) MethodNotAllowedHttpException
--
in RouteCollection.php line 255
at RouteCollection->methodNotAllowed(array('POST'))in RouteCollection.php line 242
at RouteCollection->getRouteForMethods(object(Request), array('POST'))in RouteCollection.php line 176
at RouteCollection->match(object(Request))in Router.php line 636
at Router->findRoute(object(Request))in Router.php line 625
at Router->dispatchToRoute(object(Request))in Router.php line 614
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SecureHeadersMiddleware.php line 21
at SecureHeadersMiddleware->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 31
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 31
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 62
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 163
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 104
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 55
```
This may be due to some misconfiguration on my side as i'm using lighttpd and MAYBE i mixed some rewrite rules (but doubt so, as most other features are working).

I would like to store original (not-recompressed, may be renamed, etc) photos together with gallery copies, it is possible in Lychee-Laravel?

**Comment by ildyria** [comment]
Download in Lychee-Laravel for pictures is not available.
I am surprised by the mention that the full pictures are losing quality it should not be the case.

**Comment by ABLomas** [comment]
At least on my setup it is recompressing photos, for sure. Another test:
Original: 700.38 KB (717.186 Bytes)
Downloaded "Full size": 1.37 MB (1.431.719 Bytes)

Maybe this is some kind of "large preview" and there is another way to get original photo? Going to dig into file structure, brb

**Comment by ABLomas** [comment]
I can't find original image anywhere and tested with 20 image import.
All got into "public/uploads/big" folder and are on average 83% larger than original, while keeping the same image size (in other words, they were recompressed, grow up larger and originals are deleted). "import" folder is empty and so i guess originals are not available anymore.
Size growth probably depends on original image size/quality and probably is not issue, but having original (not recompressed) image is, IMO, essential image gallery function.

**Comment by d7415** [comment]
Reproduced on master.

**Comment by ABLomas** [comment]
I think a problem is in app/ModelFunctions/PhotoFunctions.php, around line 377:

```
// Set orientation based on EXIF data
if ($photo->type === 'image/jpeg' && isset($info['orientation']) && $info['orientation'] !== '') {
           $rotation = $this->imageHandler->autoRotate($path, $info);
           $photo->width = $rotation['width'];
           $photo->height = $rotation['height'];
}


```
Commenting out this image rotation function lets us download "original" images (at least the same size).
My guess - we do not need to rotate images if they are already in "correct" orientation, as this causes recompression.
If we absolutely need to process every photo orientation, then i suggest use exiftran, or any other lossless transformation tool (exiftran can change jpeg orientation using lossless transform, including thumbnails).

**Comment by d7415** [comment]
Thanks for tracking this down.

I agree that pointless rotation is bad, and I also like the idea of using lossless rotation where required (I'm a little upset that ImageMagick can't do this). Unfortunately, I haven't yet seen a php library for this - only command line tools.

This might be a good place for an optional `exec` or `system` as with `useExifTool` on v3.

**Comment by ildyria** [comment]
I can't do anything for the previous pictures, but I can guarantee that the next ones won't have this trouble. :)
