### ISSUE TITLE
footer.blade.php not using locales for copyright text

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#121]
footer.blade.php not using locales for copyright text

**Comment by ildyria** [comment]
This requires to add locals constants to English and every others langs in 
https://github.com/LycheeOrg/Lychee-Laravel/tree/master/app/Locale

Then you take example on https://github.com/LycheeOrg/Lychee-Laravel/blob/master/resources/views/gallery.blade.php#L25

You should be able to figure out how to *localize* the footer. :)

**Comment by SerenaButler** [comment]
Which leads to think that Config::get_value('lang') is not working on landingpage

**Comment by ildyria** [comment]
which should not be the case. :(

**Comment by SerenaButler** [comment]
PR is working now :-)
