### ISSUE TITLE
Album sort by creation date is not by creation date but by id

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#123]
I added all "correct" created_at and updated_at manually (as they got not migrated when I did the migration). 

![image](https://user-images.githubusercontent.com/35893306/53965976-863e3d80-40f2-11e9-9d54-78f6bc81b3db.png)

![image](https://user-images.githubusercontent.com/35893306/53966427-6eb38480-40f3-11e9-9e33-4e5b7fca90fe.png)

It looks like it is sorting by id though.

**Comment by d7415** [comment]
Correct.

**Comment by d7415** [comment]
There are two things at play here. One is that this shouldn't happen - those new IDs seem to be in a completely different format to the rest. The other is that the created_at field does not exist in v3.

**Comment by ildyria** [comment]
new ID are actually generated from the timestamp at the time of the creation of the album. :)

**Comment by d7415** [comment]
To summarise the chat from gitter:

- v3 pads zeros on the *right* of the ID to make up to 14 chars
- Lychee-Laravel pads zeroes on the *left* of the ID to make up to 14 chars
- Some installations can provide all 14 without padding (4 sub-second digits). Some (apparently @SerenaButler's) can't.
