### ISSUE TITLE
"gallery" link results in 404 on landing page

### ISSUE THREAD

**Issue by jgbellin** [LycheeOrg/Lychee-Laravel#131]
Hi
I love so much the new landing page, but i can access to public albums and login form when activated.
Any idea ?
Good evening

![Capture](https://user-images.githubusercontent.com/43794126/54075677-461dbd00-42a2-11e9-9d18-b97c11f6c667.JPG)

**Comment by ildyria** [comment]
that is quite surprising because it is working well on my side. O.o

**Comment by ildyria** [comment]
also:
```php
Route::get('/gallery',                          'IndexController@gallery')->name('gallery');
```
so there should be no reason why you would get a 404.

**Comment by SerenaButler** [comment]
Working well here too ...

**Comment by ildyria** [comment]
wait... unless you are running Lychee like : https://example.com/something/ and then the gallery redirection points you to https://example.com/gallery instead of https://example.com/something/gallery
