### ISSUE TITLE
MethodNotAllowedHttpException error when Download Picture

### ISSUE THREAD

**Issue by brunofr29** [LycheeOrg/Lychee-Laravel#147]
thanks you for this lychee program , I installed it on the raspberry pi 3b with ubuntu server (Bionic Beaver).I am testing it and it's work fine (for a raspberry) only when I try to download or download medium or small size I have an error  --> MethodNotAllowedHttpException
![Screen Shot 03-17-19 at 08 38 AM](https://user-images.githubusercontent.com/48641547/54486987-2ed96380-4890-11e9-8005-8f69b50790a9.PNG)

how can I resolve this error , can you help me ?
Thank in advance
Bruno (french user , sorry for my poor english)

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee-Laravel/issues/97
