### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by swrap** [LycheeOrg/Lychee-Laravel#15]
I have used https://github.com/kdelfour/lychee-docker in the past for the Lychee Docker. Are there any plans to add a DockerFile as a part of this repository or create an official docker image?

**Comment by ildyria** [comment]
I don't know anything about docker. But if someone wants to create a docker image then I'm totally happy with it. :)

**Comment by ildyria** [comment]
Yep. :+1:

**Comment by ildyria** [comment]
`php artisan migrate` should have created the correct table with the correct config:

https://github.com/LycheeOrg/Lychee-Laravel/blob/master/database/migrations/2018_08_03_110942_create_configs_table.php#L40

I don't know why your value is not in the table.
Can you have a look at your database and see if the `key` `sortingPhotos_col` exists in the `configs` table?

**Comment by swrap** [comment]
It exists in the database (Postgres):

```
lychee=# SELECT * FROM configs;
...
-[ RECORD 4 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----
id    | 4
key   | checkForUpdates                                   
value | 1                                                                                                                                                                                                   
    
-[ RECORD 5 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----
id    | 5
key   | sortingPhotos_col                                 
value | takestamp                                                                                                                                                                                           
    
-[ RECORD 6 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----
...
```

**Comment by ildyria** [comment]
Thanks to @roblandry :+1: 

https://gitlab.landry.me/Dockerfile/lychee-laravel/
https://hub.docker.com/r/bigrob8181/lychee-laravel
