### ISSUE TITLE
view crashes with Undefined variable: title

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#154]
The single photo view mode (you know, the one accessible via a link displayed at the top of the share menu in photo view; basically `public/view/?p=<id>`) doesn't work with v4. I get the following error:

```
ErrorException

Undefined variable: title (View: [...]/resources/views/includes/head.blade.php)
```

I have no idea how any of that blade stuff works so somebody more knowledgeable will need to have a look...

**Comment by SerenaButler** [comment]
No problem here ... mmmm

**Comment by kamil4** [comment]
I believe you tried the "Direct Link" button at the bottom? I'm talking about copying-and-pasting the URL displayed at the top of the Share menu (or using the Twitter/Facebook/Mail buttons in there).

**Comment by SerenaButler** [comment]
Yes, sorry, I rechecked. You mean this one?

![image](https://user-images.githubusercontent.com/35893306/54835501-7dd52d80-4cc2-11e9-97e2-a6fc375de114.png)

There I get a 404 though.

**Comment by ildyria** [comment]
Both are fixed now (the URL and the view).
