### ISSUE TITLE
`composer install` on a fresh install attempts to connect to a database

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee-Laravel#160]
This is failing on a fresh install before a DB is up and running preventing it to continue installation.

**Comment by alex-phillips** [comment]
So it looks like this only happens if imagemagick is missing. Closing this.

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee-Laravel/issues/157 yup. This still need to be fixed but yeah.
