### ISSUE TITLE
Add API key

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee-Laravel#161]
Currently Laravel implements a xsrf header on login which makes it difficult to write an app (CLI) to interact with the application. Can you implement some sort of API key that if present bypasses this check? I'm writing a CLI to manage your photos / upload via the command line and the CSRF is preventing me from logging in.

Thanks!

**Comment by ildyria** [comment]
if before actually doing your interaction with the server you make a first request to `/php/index.php` you will get the CSRF token from which you can subsequently make your commands.

As for implementing an API key, this should be duable:
> ### Using a Handle method
> Another option that is unknown to many laravel users is to use a `handle` method to write some logic to avoid CSRF protection for some routes. Let’s say you want to remove CSRF protection for all routes that starts with `api/`. You can do that by visiting `VerifyCsrfToken` class located in `app/Http/Middleware/VerifyCsrfToken.php` and adding a handle method. You can simply let the request move forward if it hits routes you want to be spared. Here is how you can do it.
>
```php
public function handle($request, Closure $next){
    if ($request->is('api/*'))    {
        return $next($request);
    }
     return parent::handle($request, $next);
}
```

All is left is for someone to implement it with a api key defined in the Configs table (so users can easily modify it).

**Comment by alex-phillips** [comment]
@ildyria Thanks for the prompt reply. I've opened a PR with this functionality: https://github.com/LycheeOrg/Lychee-Laravel/pull/162

**Comment by kgnfth** [comment]
@alex-phillips @ildyria 
using api key i get empty results



for `https://*.*.*.*/api/Albums::get`
```
Headers = Authorization: my_apikey
```
Response
```
{
    "smartalbums": null,
    "albums": [],
    "shared_albums": []
}
```

and for specific private album (`https://*.*.*.*/api/Album::get`) i get
```
Headers = Authorization: my_apikey
Content = albumID=16059760845263
```
Response
`false`

What am i doing wrong ?

**Comment by ildyria** [comment]
This works perfectly fine for my server

```python
import requests
from requests.structures import CaseInsensitiveDict

url = "https://photography.viguier.nl/api/Albums::get"

headers = CaseInsensitiveDict()
headers["Accept"] = "application/json"
headers["Authorization"] = "REDACTED"
headers["Content-Type"] = "application/json"

data = """
"""

resp = requests.post(url, headers=headers, data=data)

print(resp.status_code)
print(resp.text)
```

**Comment by ildyria** [comment]
This script also works fine (it is kind of hacky and I'm sure there are better ways to do it, but to test it is enough).

```python
import requests
from requests.structures import CaseInsensitiveDict

# first we login

url = "https://photography.viguier.nl/api/Session::login"

headers = CaseInsensitiveDict()
headers["Accept"] = "application/json"
headers["Authorization"] = "REDACTED"
headers["Content-Type"] = "application/json"

data = """
{
 "username" : "REDACTED",
 "password" : "REDACTED"
}
"""

resp = requests.post(url, headers=headers, data=data)

print(resp.status_code)
print(resp.text)
cookie_session = resp.cookies.get_dict()
print(cookie_session)
# cookie_session are fucked up so we fix it.
cookie_session["lychee_session"] = cookie_session["lychee_session"][:-3] + '='
print(cookie_session)

# then we import via URL :)
url = "https://photography.viguier.nl/api/Import::url"

headers = CaseInsensitiveDict()
headers["Accept"] = "application/json"
headers["Authorization"] = "REDACTED"
headers["Content-Type"] = "application/json"

data = """
{
 "albumID" : "0",
 "url" : "https://i.imgur.com/WtUvGYL.jpeg"
}
"""

resp2 = requests.post(url, headers=headers, data=data, cookies=cookie_session)

print(resp2.status_code)
print(resp2.text)
```

**Comment by ildyria** [comment]
@alex-phillips My guess is that you are not logging in. :)

**Comment by kgnfth** [comment]
> @alex-phillips My guess is that you are not logging in. :)

![image](https://user-images.githubusercontent.com/73314940/106385637-94c22c00-63d1-11eb-868d-0447cbbe1b5a.png)
