### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mam** [LycheeOrg/Lychee-Laravel#174]
After I've done a git pull, and done php artisan migrate, I am unable to login - it is rejecting my credentials. I use a password manager so it's not because I've forgot the password.

It seems that my user has disappeared from the users table?
MariaDB [lychee]> select * from users;
Empty set (0.00 sec)

How do I recreate my user?
Thanks.

**Comment by ildyria** [comment]
if you are the admin, your credential are stored in the config table as `username` and `password`. Both of them hashed with bcrypt.

**Comment by mam** [comment]
Thanks for info. I just checked the table, and seems like the password has been stored in clear text. Not sure how that ever worked. Can I manually hash the password or what would you suggest I do?
Thanks.

**Comment by ildyria** [comment]
Empty the `values` at keys `username` and `password` then visit the website via the browser, it will trigger the re-instalation process (you won't lose data, it will just set the `username` and `password` again.

**Comment by mam** [comment]
Thanks, that worked. The username and password are now hashed in the table unlike before.

**Comment by d7415** [comment]
> seems like the username and password has been stored in clear text.

My best guess is that at some point these were changed in "More Settings" rather than the normal username/password update form.

**Comment by garster** [comment]
I somehow got into the same rut. I think my password manager overwrote the bcrypted values in the more settings screen. This issue led me to the right direction.
