### ISSUE TITLE
User's rights setting

### ISSUE THREAD

**Issue by jprokop1** [LycheeOrg/Lychee-Laravel#180]
Neither value "Allow uploads" nor "Restricted account" is visible on the users mask, although set in database
steps to reproduce: 
- create some user - set/reset "Allow uploads" and "Restricted account"; after "Save" value disappear

**Comment by ildyria** [comment]
Weird, cannot reproduce.

**Comment by jprokop1** [comment]
tested with chrome and firefox
![user_rights](https://user-images.githubusercontent.com/46556236/55884801-fedc6200-5ba8-11e9-81f7-413df86d3a1c.jpg)

**Comment by jprokop1** [comment]
closed by mistake

**Comment by ildyria** [comment]
;)

You don't have errors in the console (F12) ?

**Comment by jprokop1** [comment]
yes they are some, but not exactly on users mask...
![console_errors](https://user-images.githubusercontent.com/46556236/55885164-bbcebe80-5ba9-11e9-8e4b-615ab2868b23.jpg)

**Comment by ildyria** [comment]
and when you look at the network connection, what does it returns when they are set ?

**Comment by jprokop1** [comment]
response is true
![network](https://user-images.githubusercontent.com/46556236/55886382-e91c6c00-5bab-11e9-8b08-38e5c5f0f564.jpg)
![response](https://user-images.githubusercontent.com/46556236/55886383-e91c6c00-5bab-11e9-921e-931f8c06ffa4.jpg)

**Comment by jprokop1** [comment]
I've checked it with MySQL - it works!
It's probably due to how the boolean value is interpreted: 
MySQL does not have built-in Boolean type. However, it uses TINYINT(1) instead.
PostgreSQL provides the standard SQL type boolean.
The problem may be displaying the value true/false or 0/1

**Comment by ildyria** [comment]
that is probably the case, if you can provide a fix, we will happily merge it. :)

Thank you for covering the cornercases of PostgreSQL. :')

**Comment by jprokop1** [comment]
Since I'm not a php developer, it's hard for me to find a suitable solution.
So far I have found a difference in object $user:

user record (/UserController.php) from mysql:
{"id":1,"username":"user1","upload":1,"lock":1}

and from postgresql:
{"id":1,"username":"user1","upload":true,"lock":true} 

The value setting works.
I'm afraid a similar problem might be with all boolean database fields.

**Comment by jprokop1** [comment]
As a quick and dirty solution for me:
in app/Http/Controllers/UserController.php:
`
use Illuminate\Support\Facades\DB;

        public function list()
        {
                $users = User::all();
                if (DB::getDriverName() == 'pgsql') {
                        foreach ($users as $user) {
                                if ($user->lock == true) $user->lock = 1; 
                                if ($user->upload == true) $user->upload = 1;
                        }
                }
                return $users;
        }
`
I'm not sure if there is a more elegant solution
it works in users mask, other tests were not possible, see #192

**Comment by ildyria** [comment]
@jprokop1 thank you so much for testing these edges cases. With the last few commits it should hopefully be fixed now.
