### ISSUE TITLE
Downloading single images zipped is uneccessary ;-)

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#189]
Downloading **single** images zipped (image view!) is (usually) uneccessary ;-) Comments?

**Comment by ildyria** [comment]
I will leave the other decide on that subject. :)

**Comment by SerenaButler** [comment]
"Low Priority" tstststs .. it is more action needed to view the image (unpacking the zip) and additional software is needed too, e.g. on a smartphone  ... ;-) Honestly I really don't see sense in that but it is not good UX ;-)

**Comment by kamil4** [comment]
I don't see value in having it zipped but then, I don't really see much value in the whole Download feature in general...

**Comment by MartinHennrich** [comment]
I like the feature to download a zip of all images. 🙈

**Comment by Shrinks99** [comment]
If you're downloading a single image then yes, it should not be a zip file.  If you are downloading an album having it all contained in a folder (zip file) is useful!

**Comment by MartinHennrich** [comment]
Oh, I understand now. 😅
Yes, I agree with you. Single images should not be a zip. 👍
