### ISSUE TITLE
Feature request: SQLite

### ISSUE THREAD

**Issue by neurosatan** [LycheeOrg/Lychee-Laravel#199]
why not add SQLite? as an option because I keep just a photo gallery and cumbersome mysql I would not really like to use.

P.S. Sorry my bad eng.

**Comment by ildyria** [comment]
Lychee Laravel is database agnostic and you can use SQLite with it.
you just need to specify this in the `.env`.
Worth reading: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/config/database.php#L36
