### ISSUE TITLE
Extract and store GPS data

### ISSUE THREAD

**Issue by hermzz** [LycheeOrg/Lychee-Laravel#2]
I'd like to be able to display GPS data along with the rest of the photo info. It looks like there's already some code to extract the GPS data from the EXIF tags in [app/Photo.php](https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Photo.php#L229-L230) but it isn't stored or displayed anywhere (as far as I can see).

Ideally I'd like to store Longitude, Latitude, Elevation, and a textual description (eg: London, UK).

The question is, how do store the longitude/latitude? Both MySQL and MariaDB have geospatial fields in their newer versions (MySQL 8+ and MariaDB 10.2+ at least) and from a bit of quick research those seems like fairly extended releases (the LTS for both is 8.0 and 10.3 respectively). AWS provides both of those versions and so does Homestead.

Alternatively, we could store all them as `DECIMAL` values, but this comes with the downside of not being able to use all the fancy geospatial query functionality, like being able to find all photos within a specific range. At least not without using a third-party search engine like ElasticSearch or Lucene.

A final and more aggressive alternative (and perhaps an idea for another day) is to move all photo metadata to a JSON format and use the builtin MySQL/MariaDB JSON functions to process the data. This would provide the flexibility in the future to add metadata without creating additional fields in the photos table.

**Comment by ildyria** [comment]
I had a quick look.
https://medium.com/@brice_hartmann/getting-started-with-geospatial-data-in-laravel-94502dc74d55
But my problem is that we lose the support of Postgresql. Laravel is database agnostic. using Geometry / multi polygons in that link forces the user to use MySQL and would annoy those: https://github.com/LycheeOrg/Lychee/issues/46

Using decimal would be a solution.

As for the JSON part, it is possible with Laravel: https://www.qcode.in/use-mysql-json-field-in-laravel/
I don't have a strong opinion in this case but I am a bit annoyed to lose the direct access to the attributes via the model and `save()`. Using JSON introduces a slight overhead but I guess it is fine.

**Comment by hermzz** [comment]
All good points. PostgreSQL has had geospatial support for a while now [as an extension](https://postgis.net/) and apparently [so does SQLite](https://www.gaia-gis.it/fossil/libspatialite/index). However, I haven't been able to find a library that supports all of them, at best only [MySQL and PostgreSQL](https://github.com/eleven-lab/laravel-geo) and it'd still be a bit iffy because it'd require people to install extra stuff.

The JSON handling is already builtin to Eloquent it seems but after thinking about it you're right, it's a bit of overkill right now. I'll stick to the basic DECIMAL fields and if at some point in the future it makes sense to move the metadata to another format we can tackle the issue then.

**Comment by anthosz** [comment]
Hi,

Any news concerning this request?

Probably you can use https://fr.piwigo.org/ext/extension_view.php?eid=122 by example so that you extract Exif GPS data & maybe add a map..

**Comment by ildyria** [comment]
@hermzz was working on it. We haven't heard from him for a while unfortunately.

**Comment by tmp-hallenser** [comment]
#359 and #339 should have implemented the above mentioned features.
