### ISSUE TITLE
Missing `vendor` folder on clone

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-Laravel#20]
Laravel requires a `vendor` directory to install dependencies with composer. The fix is to `mkdir vendor` on the server, but we should consider adding an empty directory to the repo for easier installation.

**Comment by ildyria** [comment]
When distributing the release of Lychee-Laravel, I think it would be wise to distribute it with the vendor folder (after having done the `composer install`)

**Comment by erdmenchen** [comment]
Also include the Lychee-front in the 'public' folder, because it is missing when downloading this repo as a zip file currently... this results in e.g. missing svg-ressources...
