### ISSUE TITLE
LowerCamelCase vs snake_case

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#206]
#### Current practice in the config table is not consistent.

I am leaning towards snake_case.

This would need a migration and making sure that each key used in the code are actually also converted.

For someone interested in doing this, generate the migration file by doing:
`php artisan make:migration Lower_To_Snake`

This will create a file in `database/migrations` in which you will find 2 methods: `up()` and `down()`.

In the `up()` method you can add:
```php
Configs::where('key', 'checkForUpdates')->update([
	'key' => 'check_for_updates'
]);
Configs::where('key', 'deleteImported')->update([
	'key' => 'delete_imported'
]);
...
```
and of course in the `down()` method the other way around:
```php
Configs::where('key', 'check_for_updates')->update([
	'key' => 'checkForUpdates'
]);
...
```

Once you have the migration ready, you can check files in `app/...` and replace the previous config keys by the snake_cased ones.

**Comment by d7415** [comment]
lowerCamelCase looks to be how we [started](https://github.com/LycheeOrg/Lychee/blob/44d44e04fd0b0d902e5bdc213a613422dd549430/php/database/settings_content.sql) (also [here](https://github.com/LycheeOrg/Lychee/blob/1.0/php/config.php)). I'm not sure where snake slipped in :P But yeah, consistency is good!

**Comment by ildyria** [comment]
I guess it started at `image_overlay` :joy: Sorryyyy.
