### ISSUE TITLE
Add `.env` file

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-Laravel#21]
`.env.exmple` is helpful for learning how to configure Laravel, but should the repo contain a pre-configured `.env` for the user? Even an empty document so they encryption key is added to the correct place will make installation easier.

**Comment by ildyria** [comment]
If you add a `.env` then it will be tracked and you will have to ignore local changes every time: you won't be able to use `git add -u`. That is the reason why I added it to `.gitignore` and I would prefer to tell the user to do 
`cp .env.example .env`
