### ISSUE TITLE
Album sharing: is it meant to be read-only or read-write?

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#210]
It's not clear to me what the upload policy is supposed to be for shared albums (v4-style). If user `Alice` shares an album with user `Bob`, is `Bob` supposed to be able to make any changes to that album? Currently the front end thinks so, but the server generates errors (causing the front end to hang on, e.g., photo uploads).

Confusingly, `Bob` _can_ create subalbums in shared albums. Is that intentional or a bug? Certainly part of that behavior must be a server bug because it looks like a logged in user can create subalbums in _any_ album they can see, including public albums that aren't even explicitly shared with them.

In general, there is a lot of confusion in the front end about what a logged in non-admin user is allowed to do, but I'll try to document that in a separate issue, once I've collected more data...

**Comment by ildyria** [comment]
Read only.

**Comment by ildyria** [comment]
@kamil4 is it fixed now ?

**Comment by kamil4** [comment]
Yes. Completed via #211
