### ISSUE TITLE
Settings show error due to missing 'user.css' after clean install

### ISSUE THREAD

**Issue by erdmenchen** [LycheeOrg/Lychee-Laravel#22]
After a clean install of Lychee-Laravel, the app shows an error in the UI (API-Error) because it tries to load the user.css, but it is not available.

**Comment by ildyria** [comment]
Simple solution: Just create a user.css file in dist.

But I agree it should be created by the migration or an install script.

**Comment by ildyria** [comment]
This error only appears when you go in settings. But if you click once on the save button for the css. It will disappear. :)
