### ISSUE TITLE
Install fails with missing "logs" table

### ISSUE THREAD

**Issue by phillashworth** [LycheeOrg/Lychee-Laravel#221]
I'm trying to do a clean install and when I run `composer install --no-dev` I get an error about a missing "logs" table.

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Connection.php line 664:

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "logs" does not exist
  LINE 1: insert into "logs" ("type", "function", "line", "text", "upd...
                      ^ (SQL: insert into "logs" ("type", "function", "line",
   "text", "updated_at", "created_at") values (notice, App\Configs::hasImagic
  k, 171, hasImagick : false, 2019-04-28 05:54:48, 2019-04-28 05:54:48) retur
  ning "id")
```

The same error if I try `php artisan migrate`:

```
# php artisan migrate

In Connection.php line 664:

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "logs" does not exist
  LINE 1: insert into "logs" ("type", "function", "line", "text", "upd...
                      ^ (SQL: insert into "logs" ("type", "function", "line", "text", "updated_at", "created_at") values (notice, App\Configs::hasIm
  agick, 171, hasImagick : false, 2019-04-28 05:57:31, 2019-04-28 05:57:31) returning "id")

```

**Comment by ildyria** [comment]
That error is just not possible: because our CI with Travis is getting through it.
If you have an error when doing `php artisan migrate` it means that you are most likely missing dependencies in php. Something like `php-pdo`.
Can you double check you have all the required dependencies?

Another solution would be to install `php-imagick` but I guess this would still not solve the problem. :)

**Comment by phillashworth** [comment]
All the required dependencies were installed including `php-pdo`, after installing `php-imagick` it worked fine though.

**Comment by ildyria** [comment]
I will double check the install because php-imagick should only be a dependency.
