### ISSUE TITLE
thumbUrl empty for videos  

### ISSUE THREAD

**Issue by tmp-hallenser** [LycheeOrg/Lychee-Laravel#222]
When uploading videos, the column thumbURL remains empty.

I've installed ffmpeg and no error is thrown during upload.

**Comment by kamil4** [comment]
Huh... Can you send the output from the server log (`storage/logs/laravel.log`) generated while uploading a video file? Thanks!

**Comment by tmp-hallenser** [comment]
After having a look at the server log, it looks like being the same issue as #223 

Here is the server log: https://pastebin.com/jXEwWjy3

ffprobe is available at /usr/bin/ffprobe

**Comment by kamil4** [comment]
Agreed; it's the same issue as #223. I'm going to close this one to avoid duplicates. Could you indicate though what Linux distro and http server you're using?
