### ISSUE TITLE
Merging subalbum with album is greyed out

### ISSUE THREAD

**Issue by norey** [LycheeOrg/Lychee-Laravel#227]
Merging subalbum with album is greyed out.
An idea is to add another menu item in the subalbum context menu that says "Merge with parent" or something similar. This should make it faster to merge without having to scroll through lots of albums to pick the parent.

**Comment by kamil4** [comment]
I've got a fix for the greyed out part that I expect to be submitting shortly.

As to adding another menu item just for merging with the parent, I'm skeptical, but others should weigh in. I see your point about the current list becoming inconvenient with many albums but that strikes me as a more general problem that we may also need to address for other cases as well (navigation, Move), not something specific to Merge.
