### ISSUE TITLE
Cannot create new album on clean install

### ISSUE THREAD

**Issue by erdmenchen** [LycheeOrg/Lychee-Laravel#23]
After a clean install of Lychee-Laravel and migrating the DB (MariaDB), Lychee fails to create a new album, when selected in the UI, because there is a foreign key in the albums table migration with 'parent_id', that must not be empty...

**Comment by ildyria** [comment]
Weird. I will have a look.

**Comment by ildyria** [comment]
A silly mistake... Sorry.
