### ISSUE TITLE
Syntax error on new install

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-Laravel#235]
I'm doing a new Laravel install, PHP v 7.2 on a shared hosting server. After running `composer install`, it fails with the following error:

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump

Parse error: syntax error, unexpected '=' in /home/brianbe2/photos.ohheybrian.com/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 380
```

This line is throwing the error:
`380         [$value, $key] = static::explodePluckParameters($value, $key);`

**Comment by ildyria** [comment]
https://laracasts.com/discuss/channels/laravel/unexpected-illuminatesupportarrphp-on-line-388

**Comment by bennettscience** [comment]
My `phpinfo` shows Apache is using 7.2.17.

**Comment by ildyria** [comment]
The question is which php is running on CLI as composer is using the CLI.

**Comment by bennettscience** [comment]
Ok, after much digging and testing, I was able to get it running. On shared hosting with cPanel, there is a MultiPHP Manager tool which allows the user to set the PHP version per domain. Setting to 7.2 runs in the CLI but for some reason, composer doesn't see the updated version.

Running `composer install --no-dev --ignore-platform-reqs` installs all dependencies successfully and the application runs as expected. I may add a line to the wiki.

**Comment by ildyria** [comment]
yay :)
