### ISSUE TITLE
Title should follow chosen app_name

### ISSUE THREAD

**Issue by ezzra** [LycheeOrg/Lychee-Laravel#24]
The `<title>` is always lychee, but it should take the custom app_name from `.env`

**Comment by ildyria** [comment]
Good idea. :+1:

**Comment by ildyria** [comment]
It is quite easy to implement, so if someone wants to give a try.
You will need to place
```php
{{ env('app_name', 'Lychee') }}
```

in `resources/views/index.blade.php`.

Some resources: https://laravel.com/docs/5.7/blade

**Comment by bennettscience** [comment]
I'll take care of it tonight.
