### ISSUE TITLE
Can't create albums or upload pictures with non-admin users

### ISSUE THREAD

**Issue by FilippoBiga** [LycheeOrg/Lychee-Laravel#252]
### Issue
As a non-admin user, I am not able to create a new album nor to upload a picture to any album other than "Public". In particular, I can't upload pictures to an album created by the Admin who also shared it with my user. 

### Steps to reproduce – Album Creation
From the web interface, I create a new user named "newuser", with upload permissions:
<img width="735" alt="Screenshot 2019-05-10 at 17 05 03" src="https://user-images.githubusercontent.com/236585/57537087-d54c5d00-7345-11e9-8bf8-6c7b0d7fb642.png">
After that, I verify that the user has properly been inserted in the database:
```
mysql> select id, username, upload, `lock` FROM users;
+----+----------+--------+------+
| id | username | upload | lock |
+----+----------+--------+------+
|  4 | newuser  |      1 |    0 |
+----+----------+--------+------+
1 row in set (0.00 sec)
```

From a different session, I can successfully login as `newuser` through the web interface. Indeed, from the Admin panel, I see in the logs:
```
2019-05-10 15:07:22 -- notice  -- App\ModelFunctions\SessionFunctions::log_as_user -- 86 -- User (newuser) has logged in from 10.200.200.3
```
Now, as `newuser`, I try to create a new album named "Test" from the web interface ("+" -> "New Album"). However, I am presented with an error on the top bar. From the Admin session, I see in the logs:
```
2019-05-10 15:09:01 -- error   -- App\Http\Middleware\UploadCheck::album_check -- 114 -- Could not find specified album
```
In this specific case, by adding some additional logging, I could see that `$albumID` and `$user_id` are respectively `0` and `4`.

### Steps to reproduce – Picture Upload
From the Admin session, I create a new album named "Shared". Then, from "Sharing", I share that album with the user `newuser`:
<img width="668" alt="Screenshot 2019-05-10 at 17 12 15" src="https://user-images.githubusercontent.com/236585/57537541-ca45fc80-7346-11e9-8533-82e34462737f.png">
Now, by logging in as `newuser`, I can see the "Shared" album in the albums list. However, when I open the album and try to upload a picture to it, the "Uploading" panel gets stuck on "Processing":
<img width="521" alt="image" src="https://user-images.githubusercontent.com/236585/57537660-0d07d480-7347-11e9-9176-29f60d11d510.png">
From the Admin panel, I can see the same error as above in the logs:
```
 2019-05-10 15:14:00 -- error   -- App\Http\Middleware\UploadCheck::album_check -- 114 -- Could not find specified album
```
In this case, `$albumID` and `$user_id` are respectively `15575011036062` and `4`. The former is indeed the correct album id stored in the database.

Trying to upload a picture to the "Public" smart album works as expected.
---
I suppose that in [`UploadCheck::album_check`](https://github.com/LycheeOrg/Lychee-Laravel/blob/bb022a6a677b16bc12b415921c2ae9bc758911b8/app/Http/Middleware/UploadCheck.php#L112), the query fails as there's no album with such an ID that is also owned by the non-admin user. However, I am not familiar enough with the code to track down the issue further. Please let me know if there is any other information I should be providing, besides the following from "Diagnostics":
```
Diagnostics
    -----------
    Info: Latest version of PHP is 7.3

    System Information
    ------------------
    Lychee-front Version:    3.2.14
    Lychee Version (git):    bb022a6 (master) - Up to date.
    DB Version:              040000
    System:                  Linux
    PHP Version:             7.2
    MySQL Version:           5.7.26-0ubuntu0.18.04.1
    Imagick:                 1
    Imagick Active:          1
    Imagick Version:         1687
    GD Version:              2.2.5

    Config Information
    ------------------
    version:                 040000
    checkForUpdates:         1
    sortingPhotos_col:       takestamp
    sortingPhotos_order:     ASC
    sortingAlbums_col:       description
    sortingAlbums_order:     DESC
    imagick:                 1
    skipDuplicates:          0
    small_max_width:         0
    small_max_height:        360
    medium_max_width:        1920
    medium_max_height:       1080
    lang:                    en
    layout:                  1
    image_overlay:           1
    image_overlay_type:      exif
    default_license:         none
    compression_quality:     90
    full_photo:              1
    deleteImported:          1
    Mod_Frame:               0
    Mod_Frame_refresh:       30000
    landing_page_enable:     0
    landing_owner:           John Smith
    landing_title:           John Smith
    landing_subtitle:        Cat, Dogs & Humans Photography
    landing_facebook:        https://www.facebook.com/JohnSmith
    landing_flickr:          https://www.flickr.com/JohnSmith
    landing_twitter:         https://www.twitter.com/JohnSmith
    landing_instagram:       https://instagram.com/JohnSmith
    landing_youtube:         https://www.youtube.com/JohnSmith
    landing_background:      dist/cat.jpg
    thumb_2x:                1
    small_2x:                0
    medium_2x:               0
    site_title:              Lychee v4
    site_copyright_enable:   1
    site_copyright_begin:    2019
    site_copyright_end:      2019
```

**Comment by ildyria** [comment]
- Can you upload a picture to `unsorted` or `recent` ? 
- It is normal that you cannot upload a picture to an album *you do not own*.
- It is normal that you cannot create a subalbum inside an album *you do not own*.
- More worrisome: you cannot create albums. Even at the root ?

**Comment by ildyria** [comment]
You did a pretty good job at tracking the issue, I will have a better look when I can. Unfortunately, that may need to wait next week... Pretty busy weekend incoming.

**Comment by kamil4** [comment]
I second @ildyria. Album sharing in Lychee-Laravel is meant to be read-only (effectively, it's meant to act like an alternative to making an album public, but in case of sharing it's only visible by a particular user that the album is shared with).

It used to be possible to create subalbums in other users' albums, but that was basically a bug. We are making progress on fixing such issues.

**Comment by FilippoBiga** [comment]
> * Can you upload a picture to `unsorted` or `recent` ?

My bad, I hadn't tried with `recent` before. I cannot upload to `unsorted`, as I get the aforementioned error. However, I can successfully upload to `recent`. And then that picture shows up also in `unsorted`, as you would expect.

> * **It is normal if you cannot upload a picture to an album _you do not own_**.
> * **It is normal if you cannot create a subalbum inside an album _you do not own_**.

Ok, so just make sure: there is no way for me, as an Admin, to create an album, share it with a user, and let that user upload to that album?

> * More worrisome: you cannot create albums. Even at the root ?

Correct, I tried creating albums both at the root and from within an album shared with the non-admin user from the admin (but I guess in this latter case the same reasoning as above applies).

**Comment by FilippoBiga** [comment]
> I second @ildyria. Album sharing in Lychee-Laravel is meant to be read-only (effectively, it's meant to act like an alternative to making an album public, but in case of sharing it's only visible by a particular user that the album is shared with).

Ok, this answer my question from the previous comment.

**Comment by FilippoBiga** [comment]
As a temporary workaround, I did the following:
- Create the album from the Admin user
- From `mysql`, change the `owner_id` to the non-admin user I want to let upload picture to such album:
```
mysql> update albums set owner_id = 4 where id = 15575026380497;
```
- Now, logging in as the non-admin user, I am able to successfully upload pictures to that album.

**Comment by ildyria** [comment]
> Ok, so just make sure: there is no way for me, as an Admin, to create an album, share it with a user, and let that user upload to that album?

Not yet. :)

**Comment by kamil4** [comment]
I confirm that creating albums at the top level as a non-admin user is broken at the moment. I'm guessing we broke it in #244. Which is puzzling to say the least, as I could swear that I tested it before merging. Stay tuned...

**Comment by kamil4** [comment]
OK, should be fixed in #253. We actually broke it in #236.

**Comment by kamil4** [comment]
@ildyria Are you suggesting we should add an option for upload mode to album sharing?

**Comment by ildyria** [comment]
No a function to transfer ownership of an album. 

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 10 mai 2019 à 18:06, à 18:06, kamil4 <notifications@github.com> a écrit:

**Comment by kamil4** [comment]
Yeah, that would be easier :smiley:.

The ownership transfer we can already do in a round-about way: it transfers if the Admin moves an album inside somebody else's album. The subalbum can then be moved to the top level if desired. But indeed we don't currently have the means to do it in one step.

**Comment by FilippoBiga** [comment]
Thanks for taking care of this!
