### ISSUE TITLE
Laravel Debug Bar

### ISSUE THREAD

**Issue by jeyca** [LycheeOrg/Lychee-Laravel#26]
I tried to include the laravel debugbar (https://github.com/barryvdh/laravel-debugbar) to lychee. It seems to work, so javascript is loaded in the returned source code, but the div containers in html are missing. So it looks like they are not attached to the view, does anyone else succesfully added the debugbar to lychee? Or any idea what is missing here?

I did the `composer require` and a lot of cache cleanings and also added debugbar manually as provider, but none of it works.

**Comment by jeyca** [comment]
turns out there is another problem with lychee and debugbar, because there is some code sent as payload over the api:

![screenshot_2019-01-07_15-45-54](https://user-images.githubusercontent.com/37297730/50774340-75f51800-1293-11e9-9cb9-7e42ebdbe2e5.png)

I guess thats because the server does not send the data as json, so debugbar does not know that it shouldn't attach its view data here. But I remember, that lychee front does have problems when you sent json formatted data here, still need to test that.

**Comment by jeyca** [comment]
I don't remember exactly at the moment, but before when I was working with the lychee frontend, I remember that I was in trouble because in some cases lychee frontend couldn't handle simple IDs like here.

However, I noticed that the problem with debugbar does not appear when creating a new album (which also returns just an ID), and in `album::add` there is `return	Response::json($album->id, JSON_NUMERIC_CHECK);` instead of simple `return $photo->id`. 

So that very much looks like the problem, but unfortunately when changing to `return Response::json($photo->id, JSON_NUMERIC_CHECK);` it does not help. mhh...

**Comment by ildyria** [comment]
Maybe a nice alternative:
https://github.com/itsgoingd/clockwork
