### ISSUE TITLE
Git clone fails

### ISSUE THREAD

**Issue by tmp-hallenser** [LycheeOrg/Lychee-Laravel#268]
### Detailed description of the problem
Git clone currently fails. It looks like the backend points to a commit of Lychee front (d83f48c) which has been deleted.

### Steps to reproduce the issue
Try to clone the repository
`git clone --recurse-submodules https://github.com/LycheeOrg/Lychee-Laravel.git`

This results in
`Cloning into 'Lychee-Laravel'...
Submodule 'public/Lychee-front' (https://github.com/LycheeOrg/Lychee-front) registered for path 'public/Lychee-front'
Cloning into '/usr/share/nginx/html/Lychee-Laravel/public/Lychee-front'...
error: Server does not allow request for unadvertised object d83f48c75c1081733c7341e2e4946db44869bf48`

**Comment by d7415** [comment]
Thanks for pointing that out - it should be fixed in 8739396.
