### ISSUE TITLE
Sub folder display

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#27]
It would be nice to see at first glance if a folder contains subfolders.

Any idea of a visual for that ? I am not in favor of yet another ribon (like star etc).
Though a small folder discreet icon on the top right might do the trick. Other Ideas ?

**Comment by bennettscience** [comment]
A small badge on the folder thumbnail - a folder, a plus...something minimal to signify more folder inside.

**Comment by ildyria** [comment]
Proposed a solution.
https://github.com/LycheeOrg/Lychee-front/commit/91fc047610a6c2a54f9bb418e4fa02ea47e98222

I am happy with the visual but icon can be changed if required. :)
