### ISSUE TITLE
Lens model not shown in info dialog

### ISSUE THREAD

**Issue by ABLomas** [LycheeOrg/Lychee-Laravel#280]
In many pictures lens info is not displayed (shows "-" as lens model).
This applies to SEL100400GM (zoom), Voigtlander 10mm prime, some other lens (70-200 GM, Samyang 35mm...).
I guess it's due to description being too long. Exiftool reports Lens ID on SEL100400GM as "FE 100-400mm F4.5-5.6 GM OSS", on VL: "Voigtlander HELIAR-HYPER WIDE 10mm F5.6" and it can't fit into field?

Would be nice to display this info, at least as truncated value (but full field would be nice, too).

Image sample with all EXIF fields:
https://pics.lag.lt/uploads/big/6d652f7d8099dcda9b379951bcca1adf.jpg
How it's displayed in gallery: 
https://pics.lag.lt/#15511861814463/15540517913203
(press "i" and take note that lens model is displayed as "-")

**Comment by kamil4** [comment]
It appears that the EXIF extractor we are currently using in Lychee-Laravel simply fails to extract the lens info from this file. In other words, the bug is not directly in Lychee -- we simply never get any lens data.

I guess we may need to bite the bullet and investigate replacing the current extractor with something more capable. I'll post this related link here so that it doesn't get lost: https://github.com/hermzz/Lychee-Laravel/commit/386474dd12c486192eb118983f53dcf8164cd6a4

**Comment by kamil4** [comment]
FYI, I tried with Lychee v3 and the built-in EXIF extractor in that version couldn't extract the lens info either (it extracted `65535`). That version can optionally utilized exiftool though and that worked. It looks like we'll need to add support for exiftool in v4 as well...

**Comment by ABLomas** [comment]
What EXIF extractor is used in Lychee?
"Native" PHP EXIF function (php_exif.dll/php_exif.so) could extract this info, but needs some additional work.
What's interesting - i noticed that youpic.com site (picture hosting/social) also has exactly the same problems with lens models - probably the same lib/method used?

**Comment by kamil4** [comment]
We are currently using the native PHP EXIF functionality. See:

https://github.com/LycheeOrg/Lychee-Laravel/blob/75060e9be85f609f4921e8af7051990f008c379b/app/Metadata/Extractor.php#L136

If you know of a way to extract this info using the native PHP EXIF support, do not hesitate to share it/submit a PR, and we are likely to merge it.

We are thinking of switching to (or adding as an option?) [PHPExif](https://github.com/PHPExif/php-exif) which will give us exiftool support (see #363). That's probably a longer-term project, unless a volunteer steps forward.

**Comment by ABLomas** [comment]
With "native" EXIF library we can get binary (wrong-encoded) blob which can be decoded (AFAIK, i did not tested this myself just found code earlier) by swapping byte order and having additional parser.
Very bad approach and, having in mind that nobody actually cares to fix native PHP exif support (see bugreports, also commit history) i think that external tools could do better.
I tried PEL library - could extract lens info, but again, non-standart way (field at 0xA434 and requires some additional work).
That PHPExif mentioned above looks good if it could use both native and external tools (exiftool reads all info properly). But if i understood i has no "auto-switching" between methods (this should be done "manually" selecting method) and also (currently) has no method to get lens info (i just did some experiments - it gets camera model and similar stuff properly, but lens is not defined, so this requires also changes into ext library): https://github.com/PHPExif/php-exif/issues/22

I suggest very simple workaround (not a good, i know) - if other exif info is present on file (like camera model) but lens info is missing - simply do shell exec:
`exiftool -printFormat \$LensModel filename.jpg`
(if possible - optional, with default "turned off" because not all hosts can do exec on binaries or have exiftool available, or even option "exiftool location" which by default would be empty and not doing anything, but if defined by user - would be used as backup mechanism)
On my tested cameras/lens it correctly returned lens type/model and, looking into current code (except option part) does not require much work - barely 4 lines of code (more, if we need option to turn it on/off).

**Comment by d7415** [comment]
So from what you're saying...

- It sounds like we're talking about photos from "bad" devices that incorrectly encode their lens information?
- PHPExif may not be worth the effort
- We may be better off calling exiftool directly (like in v3)

**Comment by ABLomas** [comment]
>     * It sounds like we're talking about photos from "bad" devices that incorrectly encode their lens information?

I am not sure about "bad".
I have few cameras, so in short - old canon rebel or newer 6D, 5DIV works so far with any lenses i tried.
Sony - only few lens detected (kit lens on 5100/6300 or smth), most of my lenses aren't detected (but info present on EXIF).
I noticed similar issues with olympus, fuji cameras. So, i guess, they aren't "bad" devices, more likely just PHP EXIF module limitations so far?

>     * PHPExif may not be worth the effort

In it's current state - it does not extract lens info.
It's not so hard to add this into code, but then you need to bundle entire module together (see bugreport above - 3 years and counting, guess how much time it will take to integrate stuff into "mainline"), etc.
Also it's not better in any way to dirty workaround described earlier, IMO - still calls (slow) external binary ;-)

>     * We may be better off calling exiftool directly (like in v3)

At this stage - yes.
I think that my proposal above is not entirely correct - camera info will be present in EXIF in most cases, while manual lens will have many fields empty. External exiftool should be called only if "aperture" field is not empty or not zero (exif info present, lens detected).

**Comment by kamil4** [comment]
> > ```
> > * PHPExif may not be worth the effort
> > ```
> 
> In it's current state - it does not extract lens info.
> It's not so hard to add this into code, but then you need to bundle entire module together (see bugreport above - 3 years and counting, guess how much time it will take to integrate stuff into "mainline"), etc.

Looking at the commit history, the project appears to be semi-abandoned (a single commit in the last 1.5 years). I would be OK with that if it provided everything we need already but given its limited scope, I think tying ourselves to it would be a bad idea.

> > ```
> > * We may be better off calling exiftool directly (like in v3)
> > ```
> 
> At this stage - yes.
> I think that my proposal above is not entirely correct - camera info will be present in EXIF in most cases, while manual lens will have many fields empty. External exiftool should be called only if "aperture" field is not empty or not zero (exif info present, lens detected).

I think what @d7415 is suggesting is that we do _not_ mix-and-match the native reader and exiftool on a per-field basis, but rather provide two alternative, completely separate implementations, one based on the native reader (it's already there) and one based entirely on exiftool, and let the user (well, the Lychee administrator) choose. I believe this is how it works in v3.  This is also what we do with ImageMagick vs GD.  Given what we've learned, I think I would do it that way. Keep in mind that it's not just the lens info that's the problem. For instance, I have some old images from a Canon compact camera that I shot with 15+ years ago. The native exif reader appears to be unable to read ISO values from those images while exiftool works fine. Who knows how many other such cases there are with other cameras.

**Comment by kamil4** [comment]
FYI, I just checked the v3 source code and exiftool support is basically 20 lines of code that replace the call to `exif_read_data`; the rest of the extractor stays the same. We should totally do it that way!

**Comment by d7415** [comment]
> FYI, I just checked the v3 source code and exiftool support is basically 20 lines of code that replace the call to `exif_read_data`; the rest of the extractor stays the same. We should totally do it that way!

I knew the v3 code was like that (that was another reason for favouring calling `exiftool` directly - we have sample code :smile: ) but I hadn't checked/compared the v4 side.

**Comment by tmp-hallenser** [comment]
I spent some time this morning expanding PHPExif to the currently used fields by Lychee. 

I'll try to finish a first version and then you guys can have a look at it (unless you want to pursue the v3 approach).

**Comment by kamil4** [comment]
@tmp-hallenser My intuition at this point is that pursuing the v3 approach would've been less work. But if you've already invested the time and the code works and meets Lychee's requirements, I would say why not? Show us the code...

**Comment by tmp-hallenser** [comment]
@kamil4 I've just pushed my current version.

**1. Lychee-Laravel:** See this [commit](https://github.com/tmp-hallenser/Lychee-Laravel/commit/4ab0b3e3b0418f353f264f81b561f22fd5cc1bc8) (branch use_exiftool)
I've left the original functions in the code and added a primitive debug function comparing the results.

**2. php-exif:** I've forked the original repo, see branch dev (https://github.com/tmp-hallenser/php-exif/tree/dev). Here's some more work needed, a few tests are still failing (+ formatting).

**Comment by ABLomas** [comment]
Very interesting, thanks for this work!
(i'm not sure that exifinfo should be used for every photo, or when something does not work - it's much slower... But anyway, only single call on import is not so bad anyway).

Just another note - i tried with very latest PHP - it now correctly recognizes my lens ("integrated" php exif module) - so situation with php-exif module is not so bad as i was thinking before, not completely stalled ;-)
(now to write small script to re-check earlier photos and push info to DB...)

**Comment by kamil4** [comment]
> (now to write small script to re-check earlier photos and push info to DB...)

Do you mean something like this? :smiley:

https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Console/Commands/exif_lens.php

You invoke it using `artisan lychee:exif_lens`.

**Comment by ABLomas** [comment]
Oh, wow, nice that such script exists!
But currently it does nothing on my collection - on console i got output that 5 photos updated (out of 2377 - most of them missing lens info:
`SELECT count(*) FROM `photos` WHERE lens="----" or lens="" `
returns "1837" - not sure why some lens marked as "----" - but they also provide EXIF info)

Looking into code it does not update lens where info is "----" - but still:
`SELECT count(*) FROM `photos` WHERE lens="" `
returns "1486" - so those should be updated?

Not sure how it works and why it fails to select correct photos (ran another time - stilll the same result, and listed photos do not have updated EXIF):

$ php artisan lychee:exif_lens
0: EXIF updated for antakalnis4_2
1: EXIF updated for sho186
2: EXIF updated for sho91
3: EXIF updated for paukstukas55
4: EXIF updated for miestas20
$ php artisan lychee:exif_lens
0: EXIF updated for antakalnis4_2
1: EXIF updated for sho186
2: EXIF updated for sho91
3: EXIF updated for paukstukas55
4: EXIF updated for miestas20

**Comment by ildyria** [comment]
try:
```
php artisan lychee:exif_lens 5 20
```

**Comment by ABLomas** [comment]
Yes, if i understand code correctly it just sets start/number of photos to process.
But photos aren't updated at all.
Maybe this is issue with cli/web versions of PHP installations, i checked configuration files and binaries - all are using the same versions, but (only a guess) web version (i'm using FCGI via lighttpd) has exif working correctly, while CGI version does not (both load the same exif module, but i should double-check with strace/ltrace).
I check everything and will get it working, finding root cause should not be hard when script is already here and will report back, thanks! ;-)

**Comment by ABLomas** [comment]
OK, so i failed here ;-)
Script is working fine. PHP versions/libs are identical. **I just made incorrect claim that new PHP can parse photo info correctly.**
No, nothing changed actually, new PHP does NOT improved anything.
I just resized few latest photos using ON1 resizer and, while it keeps all metadata - it probably rewrites it in some way.
The same goes if i open photo in Nik - it probably rewrites metadata in some way and all info is recognized in PHP.
Photos straight from raw developer (DxO, LR) still have the same issue - PHP can't parse lens data.

...but now, when i know about this script - it will be easy to modify it so it would work using exiftool ;-)

**Comment by ABLomas** [comment]
I modified script a bit to use exiftool and ran trough my collection (~2.4K images) without issues.
Looks much better now, having this fixed in current code would be nice, but even now it's good enough ;-)

In case someone needs - replace foreach with this:
`                foreach ($photos as $photo) {
                        $url = Storage::path('big/' . $photo->url);
                        if (file_exists($url)) {
                                // $info = $this->metadataExtractor->extract($url, $photo->type); // original line, using PHP EXIF functions
                                $this->line('Processing: ' . $url);
                                eval('$info=' . `exiftool -php -q $url`);
                                if ($photo->size == '' && isset($info[0]['FileSize'])) {
                                        $photo->size = $info[0]['FileSize'];
                                }
                                if ($photo->iso == '' && isset($info[0]['ISO'])) {
                                        $photo->iso = $info[0]['ISO'];
                                }
                                if ($photo->aperture == '' && isset($info[0]['ApertureValue'])) {
                                        $photo->aperture = $info[0]['ApertureValue'];
                                }
                                if ($photo->make == '' && isset($info[0]['Make'])) {
                                        $photo->make = $info[0]['Make'];
                                }
                                if ($photo->getAttribute('model') == '' && isset($info[0]['Model'])) {
                                        $photo->setAttribute('model', $info[0]['Model']);
                                }
                                if ($photo->lens == '' || $photo->lens == '----') {
                                        if (isset($info[0]['LensModel'])) {
                                                $photo->lens = $info[0]['LensModel'];
                                        } elseif (isset($info[0]['LensInfo'])) {
                                                $photo->lens = $info[0]['LensInfo'];
                                        } elseif (isset($info[0]['LensType'])) {
                                                $photo->lens = $info[0]['LensType'];
                                        } else {
                                                 $photo->lens = "Manual Lens";
                                        }
                                        $this->line($i . ': Updating lens: ' .$photo->lens . ' for ' . $photo->title);
                                }
                                if ($photo->shutter == '' && isset($info[0]['ShutterSpeedValue'])) {
                                        $photo->shutter = $info[0]['ShutterSpeedValue'];
                                }
                                if ($photo->focal == '' && isset($info[0]['FocalLength'])) {
                                        $photo->focal = $info[0]['FocalLength'];
                                }
                                if ($photo->save()) {
                                        $this->line($i . ': EXIF updated for ' . $photo->title);
                                } else {
                                        $this->line($i . ': Could not get EXIF data/nothing to update for ' . $photo->title . '.');
                                }
                        } else {
                                $this->line($i . ': File does not exists for ' . $photo->title . '.');
                        }
                        $i++;
                }
`

**Comment by tmp-hallenser** [comment]
> @tmp-hallenser My intuition at this point is that pursuing the v3 approach would've been less work. But if you've already invested the time and the code works and meets Lychee's requirements, I would say why not? Show us the code...

Any guidance which approach to pursue? 
I'm working on the #378 enhancement which requires exiftool to read the required parameters.

**Comment by tmp-hallenser** [comment]
#401 should fix this
