### ISSUE TITLE
Request: Provide documentation for API

### ISSUE THREAD

**Issue by kenokenobingo** [LycheeOrg/Lychee-Laravel#283]
I’d like to create alternative clients and front-ends for the Lychee API, but I couldn’t find a documentation.

**Comment by ildyria** [comment]
Still incomplete but a copy of the document is here:
https://github.com/LycheeOrg/Lychee-Laravel/wiki/Server-API

**Comment by ildyria** [comment]
Updated: https://github.com/LycheeOrg/Lychee-Laravel/wiki/Server-API
