### ISSUE TITLE
Album download does not work

### ISSUE THREAD

**Issue by Vorlif** [LycheeOrg/Lychee-Laravel#299]
### Detailed description of the problem
When I try to download an album I only get an empty zip file. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Open an album
2. Click on the `Download Album` button
3. Save the zip file to system
4. Open the zip file.
5. The zip file is empty.

### Output of the diagnostics
```text
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.

System Information
------------------
Lychee-front Version:      3.2.16
Lychee Version (git):      64d9436 (master) - Up to date.
DB Version:                040000
System:                    Linux
PHP Version:               7.3
PostgreSQL Version:        PostgreSQL 11.4 (Debian 11.4-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

Lychee total space:        183.05 MB
Upload folder space:       126.36 MB
System total space:        55.27 GB
System free space:         48.38 GB (87%)

Imagick:                   1
Imagick Active:            1
Imagick Version:           1687
GD Version:                2.2.5

Config Information
------------------
version:                   040000
checkForUpdates:           1
layout:                    1
image_overlay:             1
image_overlay_type:        exif
full_photo:                1
Mod_Frame:                 0
Mod_Frame_refresh:         30000
landing_twitter:           
landing_instagram:         
landing_youtube:           
landing_owner:             User
landing_title:             User
landing_page_enable:       0
compression_quality:       94
site_title:                Fotos
lang:                      en
sortingPhotos_col:         takestamp
sortingPhotos_order:       ASC
sortingAlbums_col:         description
sortingAlbums_order:       DESC
imagick:                   1
skipDuplicates:            0
small_max_width:           0
small_max_height:          360
medium_max_width:          1920
medium_max_height:         1080
default_license:           none
deleteImported:            1
landing_subtitle:          Cat, Dogs & Humans Photography
landing_background:        dist/cat.jpg
thumb_2x:                  1
small_2x:                  0
medium_2x:                 0
site_copyright_enable:     1
site_copyright_begin:      2019
site_copyright_end:        2019
additional_footer_text:    
display_social_in_gallery: 0
public_recent:             0
recent_age:                1
public_starred:            0
public_search:             0
landing_facebook:          
landing_flickr:          
```

### Lychee log output
```text
2019-07-07 18:30:11 -- error   -- App\Http\Controllers\{closure} -- 668 -- Original photo missing: 30fa778d7308c84d6491d2c2f869973b.JPG
2019-07-07 18:30:11 -- error   -- App\Http\Controllers\{closure} -- 668 -- Original photo missing: e7a255a5548717aa8d7619512d663b98.JPG
2019-07-07 18:30:11 -- notice  -- App\Http\Controllers\AlbumController::getArchive -- 627 -- test has been downloaded.
```

The album contains two pictures. The following files exist:
```text
host# find ./ -name "30fa778d7308c84d6491d2c2f869973b*"
./uploads/big/30fa778d7308c84d6491d2c2f869973b.JPG
./uploads/small/30fa778d7308c84d6491d2c2f869973b.JPG
./uploads/medium/30fa778d7308c84d6491d2c2f869973b.JPG
./uploads/thumb/30fa778d7308c84d6491d2c2f869973b@2x.jpeg
./uploads/thumb/30fa778d7308c84d6491d2c2f869973b.jpeg

host# find ./ -name "e7a255a5548717aa8d7619512d663b98*"
./uploads/big/e7a255a5548717aa8d7619512d663b98.JPG
./uploads/small/e7a255a5548717aa8d7619512d663b98.JPG
./uploads/medium/e7a255a5548717aa8d7619512d663b98.JPG
./uploads/thumb/e7a255a5548717aa8d7619512d663b98.jpeg
./uploads/thumb/e7a255a5548717aa8d7619512d663b98@2x.jpeg
```

### Browser and system

* Firefox 67.0.4 (64-Bit)
* Arch Linux / Kernel 5.1.16

**Comment by kamil4** [comment]
Sorry, you were unlucky enough to catch us in the middle of some refactoring. @ildyria implemented new storage abstraction as part of 64d943627ccb959ffa7f3d735b288b47c364c041. This requires making some (trivial) changes all over the code; he did not make them in the download code, presumably because he knew that I was working in that area and he didn't want to complicate my future merge. When my https://github.com/LycheeOrg/Lychee-Laravel/pull/296 PR is merged, this problem will be resolved. This should be some time later this week, after I make a few more changes on my branch.

**Comment by Vorlif** [comment]
Thanks for the quick answer. Nothing to be sorry about, I was aware that I was using a development version. Do you already know if I will have to do a reinstall or will the changes be backward compatible? Should I generally calculate with breaks in the Laravel version that require a new installation?

Thanks for your work!

**Comment by ildyria** [comment]
@Vorlif To update you will juste need to go to `Diagnostics` and you will see an `Update` button on top of the page. This will take care of getting updating the code and the database when required.

No need to reinstall etc. If we break something by changing the code, the (hopefully) next update will fix it when available (unless we really f**k up :sweat_smile: ). We have a decent test suite which we still need to improve (we have about 50% code coverage, making sure basic functionalities are working).

However if you manually changed some settings to undesirable values, but then you are on your own (I will actually try to make some change that would fix that in some future changes).

**Comment by ildyria** [comment]
> Thanks for the quick answer. Nothing to be sorry about, I was aware that I was using a development version.

It is a development version, but I consider it to be pretty close to a beta stage. Once those [issues](https://github.com/LycheeOrg/Lychee-Laravel/milestone/1) are fixed we will be releasing it. We still need to discuss the way we will do that internally (do we migrate the change? do we create a migration script? etc...)

> Do you already know if I will have to do a reinstall or will the changes be backward compatible? Should I generally calculate with breaks in the Laravel version that require a new installation?

We are doing some an incremental development and you can see our system as some sort of rolling release (through commits). Unless you change something very specific in the configuration (like the location of your pictures in that case), most of changes are usually backward compatible. What I mean by that is if you really needed to, you can just do the following to get back to the previous versions:
```
git reset --hard HEAD^<insert number of commits since the last update>
./artisan migrate:rollback
```

**Comment by Vorlif** [comment]
@ildyria Thanks for the explanations. I thought the repository is still in alpha status since the last release was an alpha version. But it's nice to hear that it's already the basis for the next release. 

I was just unsure if there were any downward compatible changes yet, but if the master represents something like the current version I will continue to use them. Then I can continue uploading pictures. :relaxed:
