### ISSUE TITLE
Download button does not work with Android Chrome

### ISSUE THREAD

**Issue by Vorlif** [LycheeOrg/Lychee-Laravel#305]
### Detailed description of the problem
If you try to download a picture with the `Download` button under Android Chrome you will be redirected to the overview and nothing happens.

No problems with Firefox for Android. Therefore, probably more of a frontend problem?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Open an album
2. Open an image
3. Open the *three-point-menu*
4. Press the `Download` button

### Output of the diagnostics
```text
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.

System Information
------------------
Lychee-front Version:      3.2.16
Lychee Version (git):      7ccd77f (master) - Up to date.
DB Version:                040000
System:                    Linux
PHP Version:               7.3
PostgreSQL Version:        PostgreSQL 11.4 (Debian 11.4-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

Lychee total space:        225.87 MB
Upload folder space:       169.20 MB
System total space:        55.27 GB
System free space:         48.26 GB (87%)

Imagick:                   1
Imagick Active:            1
Imagick Version:           1687
GD Version:                2.2.5

Config Information
------------------
version:                   040000
checkForUpdates:           1
layout:                    1
image_overlay:             1
image_overlay_type:        exif
full_photo:                1
Mod_Frame:                 0
Mod_Frame_refresh:         30000
landing_twitter:           
landing_instagram:         
landing_youtube:           
landing_page_enable:       0
compression_quality:       94
site_title:                Lychee v4
landing_owner:             Photographen
sortingPhotos_col:         takestamp
sortingPhotos_order:       ASC
sortingAlbums_col:         description
sortingAlbums_order:       DESC
imagick:                   1
skipDuplicates:            0
small_max_width:           0
small_max_height:          360
medium_max_width:          1920
medium_max_height:         1080
default_license:           none
deleteImported:            1
landing_subtitle:          Cat, Dogs & Humans Photography
landing_title:             Photographen
landing_background:        dist/cat.jpg
thumb_2x:                  1
small_2x:                  0
medium_2x:                 0
site_copyright_begin:      2019
site_copyright_end:        2019
additional_footer_text:    
display_social_in_gallery: 0
public_recent:             0
recent_age:                1
public_starred:            0
site_copyright_enable:     0
public_search:             0
landing_facebook:          
landing_flickr:            
lang:                      en
downloadable:              0
```

### Browser and system
* Google Chrome for Android (75.0.3770.101)
* Android 8.0

**Comment by kamil4** [comment]
I can't reproduce it, using the exact same version of Chrome as you reported.

In my experience, Chrome can be pretty aggressive with caching, and there's no easy way to force a reload from the server with the Android version. So it could be that the front end code it's running in your browser is older than the version on the server (and we made a change to the download protocol with the latest commit so the front end and the server *must* be in sync for downloads to work). Could you close Lychee, try wiping out the browser cache (it will give you the option to choose the domains to clear after you click on "Clear data") and load Lychee again?

**Comment by Vorlif** [comment]
Thanks, that's it.
I adjusted my Nginx configuration to avoid such problems soon.

Before that:
```text
# serve static files directly
location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
  access_log off;
  expires max;
  log_not_found off;
}
```

After that:
```text
# serve static files directly
location ~* (.+)\.(?:\w+)\.(bmp|css|cur|gif|ico|jpe?g|m?js|png|svgz?|webp|webmanifest|html)$ {
  access_log off;
  log_not_found off;
  try_files $uri $1.$2;
}
```

This enables [Filename-based cache busting](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/web_performance_filename-based_cache_busting.conf) and sets the `last-modified` header to the last modified date of the file.

Maybe you'd like to customize [your configuration](https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install#74-edit-nginx-config-only-on-nginx-server), too.

**Comment by kamil4** [comment]
Agreed, what we have in the wiki is basically asking for trouble...

I can't find a clear explanation of what that `try_files` does. Personally I would be in favor of simply removing the `expires max;` line instead. @Vorlif would that work? Based on the nginx docs I'm guessing that would keep caching disabled...

**Comment by d7415** [comment]
> Personally I would be in favor of simply removing the `expires max;` line instead. 

I'm inclined to agree. My personal nginx config for this project is *much* simpler... Despite including some unnecessary blocks from v3... *sigh* another thing for the list...
