### ISSUE TITLE
Private photos still show "Make Private" in the menu

### ISSUE THREAD

**Issue by matthijskooijman** [LycheeOrg/Lychee-Laravel#309]
### Detailed description of the problem
When a photo was made private, the menu item to make it public again is called "Make private".

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to any uploaded photograph
2. Click on the eye icon in the top right
3. Click on "Make private" to make it private
4. If you now navigate back the the album, the photo has an icon to indicate its privateness.
5. If you click the eye icon for the photo again, it still shows "Make private", rather than "Make public". Clicking it *does* clear the privatness of the photo (at least it clears the icon in the album).

### Output of the diagnostics
Diagnostics
    -----------
    Info: Latest version of PHP is 7.3
    Warning: 'dist/user.css' does not exist or has insufficient read/write privileges.
    Warning: 'dist/' has insufficient read/write privileges.
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      -
    Lychee Version (git):      2270caf (master) - Up to date.
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.2
    MySQL Version:             10.3.13-MariaDB-2
    
    Lychee total space:        114.50 MB
    Upload folder space:       61.18 MB
    System total space:        62.50 GB
    System free space:         4.15 GB (6%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        description
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    1
    image_overlay:             1
    image_overlay_type:        exif
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           1
    Mod_Frame:                 0
    Mod_Frame_refresh:         30000
    landing_page_enable:       1
    landing_owner:             John Smith1
    landing_title:             John Smith2
    landing_subtitle:          Cat, Dogs & Humans Photography
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            https://www.flickr.com/JohnSmith
    landing_twitter:           https://www.twitter.com/JohnSmith
    landing_instagram:         https://instagram.com/JohnSmith
    landing_youtube:           https://www.youtube.com/JohnSmith
    landing_background:        dist/cat.jpg
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    site_title:                Lychee v4
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2021
    public_search:             0
    additional_footer_text:    
    display_social_in_gallery: 0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1

### Browser and system
Firefox on Ubuntu disco (also running Lychee on there)

**Comment by matthijskooijman** [comment]
Hm, it seems I got things reversed: The photo is actually private to start with, and when first selecting the "Make private" option, it becomes public (that is, it shows up in the "Public" meta album, and gets an icon). Also, it seems this only works in a private album, in a public album I get a prompt saying you should change the album properties to make a picture private.

**Comment by matthijskooijman** [comment]
Ah, after some more experimentation, this seems to be PEBCAK. Apparentely when you click the eye icon when the photo is private, you make it public (it turns orange as well), as well as opening the sharing menu to copy the link. I guess this makes sense, but it is different from how you make an album public, which confused me. Since things actually work as intended (I assume), I'm closing this issue (but there might be some UI improvements to be made here).

**Comment by kamil4** [comment]
Yeah, as you found out, there is logic behind the current behavior but it is not immediately obvious/intuitive to a newcomer. We've been recently discussing these issues in https://github.com/LycheeOrg/Lychee-front/issues/119, without a workable conclusion so far. We could split up that menu but we worry how increasing the already significant number of icons in the menu bar will affect the experience on mobile...
