### ISSUE TITLE
Can't get video thumbs

### ISSUE THREAD

**Issue by jgbellin** [LycheeOrg/Lychee-Laravel#31]
Hi 

Everything works well in my install but I can't get php-ffmpeg installed correctly :

```
composer require php-ffmpeg/php-ffmpeg
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Do not run ComposUsing version ^0.13.0 for php-ffmpeg/php-ffmpeg
./composer.json has been updated
Loading composer repositories with package infoUpdating dependencies (including require-dev)         Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: bepsvpt/secure-headers
Discovered Package: fideloper/proxy
Discovered Package: laravel/nexmo-notification-channel
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pbmedia/laravel-ffmpeg
Package manifest generated successfully.
```
I guess it should appear in discovered, but it isn't, any idea ?

**Comment by ildyria** [comment]
I have never used ffmpeg before but yes it should be in the autoload.php.

**Comment by jgbellin** [comment]
i can see it in the autoload_classmap.php, 
but I always have the "Could not create thumbnail for video because FFMPEG is not available" error in lychee's logs when I import a new video.
Here is the imported video screenshot :
![capture](https://user-images.githubusercontent.com/43794126/51393230-829d2a00-1b37-11e9-80c4-4ad5d349487d.PNG)

I hope this helps ...

**Comment by d7415** [comment]
I haven't properly looked at laravel yet, but [this](https://github.com/LycheeOrg/Lychee/wiki/FAQ#why-dont-my-videos-have-thumbnails) *might* be relevant.

**Comment by jgbellin** [comment]
Thank so much, I have tried but same result, here the log :

> 2019-01-19 00:17:19 -- notice -- App\Http\Controllers\PhotoController::add -- 275 -- Could not create thumbnail for video because FFMPEG is not available.

**Comment by jgbellin** [comment]
Now I tried to do [this](https://github.com/LycheeOrg/Lychee/pull/99) and still no thuhmb but a new error :

`2019-01-19 00:30:24 -- error -- App\Http\Controllers\PhotoController::add -- 282 -- Could not create thumbnail for video`

**Comment by ildyria** [comment]
@jgbellin Well this means that you are making progress. As it now shows that you are actually trying to create the thumbnail.

**Comment by ildyria** [comment]
Did you apply: https://github.com/LycheeOrg/Lychee/wiki/FAQ#why-dont-my-videos-have-thumbnails
here: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Photo.php#L547
?

**Comment by jgbellin** [comment]
great, the last update fixed my problem, thx a lot !
