### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by ouafnico** [LycheeOrg/Lychee-Laravel#310]
### Detailed description of the problem
Composer fail with following error when installing Lychee v4.

-> # sudo  -u www-data composer install --no-dev
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  

I'm running Debian 9 with php7.3.

I'm following : https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install-Steps-on-Debian-(Testing)

**Comment by ouafnico** [comment]
It works with newer composer version.

Maybe we can add it on the wiki.

For debian 9, remove the composer package.
Follow this howto to upgrade:
https://tecadmin.net/install-php-composer-debian/

**Comment by d7415** [comment]
I don't mind a quick mention, but so long as this works in Buster (Debian 10, which is now stable) I'm not especially bothered about Stretch/9/oldstable.
