### ISSUE TITLE
Do we really need writable `app/`?

### ISSUE THREAD

**Issue by matthijskooijman** [LycheeOrg/Lychee-Laravel#311]
The docs say that the `app/` directory must be writable, but that directory contains most of the PHP code. Why is this needed? I'm usually hesitant to make PHP code writable by the webserver (and for extra security, it often makes sense to even forbid execution of PHP code in a webserver-writable directory).

I think I've noticed that Laravel actually generates PHP code for views, but does it also make changes to existing files? If not, would it be sufficient to make just some subdirectory writable?

**Comment by kamil4** [comment]
Short answer: Lychee-Laravel will work without a writable `app/` folder.

However, if you want to be able to update your Lychee installation with a click of a button in the web browser (which is supported with Lychee-Laravel, though it's disabled by default), your whole Lychee installation tree (and not just `app/`) must be http-writable.

As far as I know, the minimum set of directories that need to be http-writable is as follows:
```
storage/framework/sessions
storage/framework/views
storage/logs
public/uploads
public/uploads/small
public/uploads/big
public/uploads/thumb
public/uploads/medium
public/uploads/import
public/dist
```

**Comment by matthijskooijman** [comment]
> However, if you want to be able to update your Lychee installation with a click of a button in the web browser (which is supported with Lychee-Laravel, though it's disabled by default), your whole Lychee installation tree (and not just app/) must be http-writable.

Ah, that makes sense (but would be good to make that explicit). Things indeed seem to work fine without a writeable `app` directory.


Slightly expanding the topic of this issue, but would it perhaps make sense to reduce the number of directories that need to have their permissions changed? Ideally, there would be only a single writable directory and everything else lives under there. Practically, you'd probably need one inside `public` and one outside, but that could perhaps be done? e.g. have `storage` and `public/storage` writeable and nothing else (moving `public/uploads` and `public/dist/user.css` [seems to be the only file written there] into `public/storage`). Probably messy to get migrations on existing installations right, though.

The reason I bring this up is a bit convoluted, but I'll go into it anyway: I noticed that a bunch of files in the repo are marked as executable, when there is no need for that (and the script I used to give my webserver permissions removed executable bits, so I was left with a dirty working copy). I was preparing a PR to fix that, when I realized this is probably because of the `chmod -R 775` suggested by the install wiki page, so removing those executable bits from the repository would cause those files to become changed when you chmod like suggested. You can't fix this by doing 644 chmod, since that removes the +x you need on directories. While writing this I realize that you could simply recommend `chmod -R g+w` instead, maybe.

Alternatively (and this was what I had in mind when I started writing this), you could chmod only the directories that need to be writable (non-recursively), which would leave alone any git-tracked files. However, there are currently quite some directories, as listed above, to chmod then. So I thought, maybe reduce that list a bit (which also means that the code should be creating some of these directories automatically, so they get the right writable permissions autoamtically).

One more somewhat related question: what is the point of the `storage/app` directory? It only contains an empty `views` directory, but is not in your list of writable directories, so it can never become non-empty? Can it be removed from the repo? Or should it be in your list of writable directories?

Apologies for the braindump, but permissions are just messy...

**Comment by ildyria** [comment]
Added to FAQ

**Comment by agottschling** [comment]
I hate to use a closed issue for this, but it seemed to be the best place to note this. Setting app/* to 755 prevents a git pull in my testing. Git noted the difference between the repo's 644 permissions on app/ and the install guide requires setting app/ to 755. Don't know how this would be fixed, but figured it should be noted somewhere.

**Comment by kamil4** [comment]
Thank you for your input. We will clean this area up, including changing the documentation so that it doesn't recommend actions that make subsequent git updates fail.
