### ISSUE TITLE
[Enhancement] Show "delete" checkbox on server import dialog

### ISSUE THREAD

**Issue by matthijskooijman** [LycheeOrg/Lychee-Laravel#313]
When you import files from the server, these are deleted by default. This can be toggled in the (advanced) settings, but it would be nicer if you can (also) toggle this on each import separately, i.e. by adding a checkbox here:

![image](https://user-images.githubusercontent.com/194491/62327336-a2cb7f80-b4b0-11e9-9264-0f6aaeb56cbc.png)

On a related note, the above dialog currently warns that files will be deleted even when the config entry for that is disabled, which is a bit misleading (but that would also be fixed if a checkbox was added).

**Comment by kamil4** [comment]
I agree wholeheartedly :smiley:.
