### ISSUE TITLE
Log client IPs from behind Cloudflare

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-Laravel#314]
Thank you very much for the help!  I wasn't able to get X-Forwarded-For to work, but I was able to get the following to work:

`($_SERVER['HTTP_CF_CONNECTING_IP'] ?? $_SERVER['HTTP_X_REAL_IP'] ?? $_SERVER['REMOTE_ADDR']));`

How can I request that this be put into Version 4?  Thanks!

_Originally posted by @SicAlpha in https://github.com/LycheeOrg/Lychee/issues/281#issuecomment-520022210_

**Comment by ildyria** [comment]
Already implemented in Laravel. :sunglasses: 

See here:
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Http/Middleware/TrustProxies.php

You just need to add the proxy of Cloudfare to the list.

**Comment by SicAlpha** [comment]
I'm using this image for Lychee:
https://hub.docker.com/r/linuxserver/lychee/

Does Laravel work with it?  Apologies if this is a stupid question, I'm pretty new to all of this and setting it up at home for fun/learning.

**Comment by d7415** [comment]
> You just need to add the proxy of Cloudfare to the list.

That sounds like it could be painful... In my experience using other websites behind Cloudflare, they connect from multiple IPs.

> Does Laravel work with it?

I don't know. [Lychee-Laravel-Docker](https://github.com/LycheeOrg/Lychee-Laravel-Docker) should though.

**Comment by ildyria** [comment]
About cloudfare, some readings if someone wants to implement it :

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
https://qiita.com/ziming/items/575355bdf383b1ec4d92
https://medium.com/@panjeh/laravel-cloudflare-logging-real-visitor-ip-address-server-solution-1e9739e89654
https://thisinterestsme.com/php-ip-address-cloudflare/
https://github.com/cloudflarearchive/Cloudflare-Tools/blob/master/cf-joomla/plgCloudFlare/ip_in_range.php

**Comment by ildyria** [comment]
Also worth to have a look : https://github.com/monicahq/laravel-cloudflare :D

**Comment by d7415** [comment]
> Also worth to have a look : https://github.com/monicahq/laravel-cloudflare :D

At a quick glance, this looks like it would be good as a FAQ entry, removing the need for a patch.

**Comment by d7415** [comment]
Added to [FAQ](https://lycheeorg.github.io/docs/faq.html#how-can-i-see-the-correct-client-ip-address-when-running-lychee-behind-cloudflare)
