### ISSUE TITLE
Interim release after the February Alpha?

### ISSUE THREAD

**Issue by mannp** [LycheeOrg/Lychee-Laravel#315]
Hi all, not meant as a chaser, just a general question.

Its been a while since the initial alpha release back in Feb and wondered if you were planning an interim release / beta anytime soon?

Cheers

Edit: I should add, I've noted a 'dev' build of the docker image and wondered if that was suitable by way of an updated git? Or we should steer clear until a formal release?

**Comment by ildyria** [comment]
Actual v4 is pretty close as you can see in the Milestone:

https://github.com/LycheeOrg/Lychee-Laravel/milestone/1

I'm still considering whether to implement the RAW upload... or not!

What is mostly left to do is the documentation/wiki part.

**Comment by mannp** [comment]
Cool okay thanks for taking the time to update us :)

I've just started using this one -> bigrob8181/lychee-laravel:dev which I have assumed is the current git build anyway? If so there is a way to get the latest in docker at least, without a formal release.

Personally I am more wanting a solid release so the first two are important, the rest for me not so, but I am sure others might disagree :)

**Comment by ildyria** [comment]
I will create a Release Candidate once this is merged: https://github.com/LycheeOrg/Lychee-front/issues/119

**Comment by kamil4** [comment]
> I will create a Release Candidate once this is merged: [LycheeOrg/Lychee-front#119](https://github.com/LycheeOrg/Lychee-front/issues/119)

Challenge accepted :wink:.

**Comment by ildyria** [comment]
Oh right I think I promised a release...

**Comment by ildyria** [comment]
Fixed.
