### ISSUE TITLE
Importing returns 404

### ISSUE THREAD

**Issue by yungdan1** [LycheeOrg/Lychee-Laravel#33]
Import::server and Import::url simply returns 404. No pictures are imported from directory or from link.

Diagnostics
-----------
Error: No or wrong property for identifier in database

System Information
------------------
Lychee Version:  3.2.9
DB Version:      040000
System:          Linux
PHP Version:     7.3
MySQL Version:   10.1.37-MariaDB-0+deb9u1
Imagick:         1
Imagick Active:  1
Imagick Version: 1687
GD Version:      2.2.5

**Comment by ildyria** [comment]
> Import::server

is not implemented. still in the Todo.

> Import::url

I thought that one was implemented. Something is weird here.

**Comment by ildyria** [comment]
My mistake neither have been implemented yet.

**Comment by scratcher28** [comment]
please implement Import as soon as possible ;)

**Comment by ildyria** [comment]
@scratcher28  @yungdan1 Done.
And as a bonus when you import, your folder tree will be replicated in Lychee (only visual, not in the [small/medium/big] folder).
