### ISSUE TITLE
Lychee-Laravel cannot be updated using `git pull`

### ISSUE THREAD

**Issue by agottschling** [LycheeOrg/Lychee-Laravel#338]
### Detailed description of the problem
*A clear and concise description of what the bug is.*
When trying to update Lychee to the latest commit, git pull fails. 
### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'lychee directory on your webserver'
2. `git pull`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

agottschling@hoxton /v/w/*********> sudo git pull
[sudo] password for agottschling:
warning: redirecting to https://github.com/LycheeOrg/Lychee-Laravel.git/
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 78 (delta 49), reused 55 (delta 40), pack-reused 2
Unpacking objects: 100% (78/78), done.
From https://www.github.com/LycheeOrg/Lychee-Laravel
   0bcde27..93448cc  master     -> origin/master
Fetching submodule public/Lychee-front
From https://github.com/LycheeOrg/Lychee-front
   5064715..d8612bf  master     -> origin/master
Updating 0bcde27..93448cc
error: Your local changes to the following files would be overwritten by merge:
        app/Http/Controllers/AlbumController.php
        app/Http/Controllers/FrameController.php
        app/Http/Controllers/ImportController.php
        app/Http/Controllers/PhotoController.php
        app/Http/Controllers/SettingsController.php
        app/Locale/ChineseSimplified.php
        app/Locale/Dutch.php
        app/Locale/English.php
        app/Locale/French.php
        app/Locale/German.php
        app/Locale/Italian.php
        app/Locale/Swedish.php
        app/Locale/slovak.php
        app/Metadata/Extractor.php
        app/ModelFunctions/PhotoFunctions.php
        app/ModelFunctions/SymLinkFunctions.php
        app/Photo.php
        app/SymLink.php
Please commit your changes or stash them before you merge.
Aborting

### Output of the diagnostics
*(Settings => Diagnostics or https://example.com/Diagnostics )*
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.3
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      0bcde27 (master) - 4 commits behind master (93448cc)
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.2
    MySQL Version:             5.7.27-0ubuntu0.18.04.1
    
    Lychee total space:        2.59 GB
    Upload folder space:       2.53 GB
    System total space:        24.15 GB
    System free space:         3.31 GB (13%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1687
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        description
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    1
    image_overlay:             1
    image_overlay_type:        exif
    default_license:           reserved
    compression_quality:       90
    full_photo:                1
    delete_imported:           1
    Mod_Frame:                 0
    Mod_Frame_refresh:         30000
    landing_page_enable:       1
    landing_owner:             Andrew Gottschling
    landing_title:             Gottschling Photography
    landing_subtitle:          Landscape, Portrait, and Sports Photography
    landing_facebook:          
    landing_flickr:            
    landing_twitter:           https://www.twitter.com/@i0sen
    landing_instagram:         https://instagram.com/@i0s3n
    landing_youtube:           
    landing_background:        dist/cat.jpg
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    site_title:                gPhoto Client System
    site_copyright_enable:     1
    site_copyright_begin:      2017
    site_copyright_end:        2019
    public_search:             0
    additional_footer_text:    
    display_social_in_gallery: 0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1

### Browser and system
WIN10-1903 - FF Latest

**Comment by kamil4** [comment]
I'm guessing these might be simply permission bit changes? What does `git diff --summary` invoked in your Lychee directory say? If it is just the permissions, you should be able to stash them (`git stash`) before rerunning `git pull`. You may also want to check, e.g., https://stackoverflow.com/questions/6476513/git-file-permissions-on-windows for more general hints on how to deal with such issues on Windows.

**Comment by agottschling** [comment]
Ok. Thanks for the insight. Anything else I've got to do other than a pull to update?

**Comment by kamil4** [comment]
After a pull, it's recommended to run `php artisan migrate` to update your database. Other than that, things should be good to go!

**Comment by agottschling** [comment]
Gotcha. Thanks
