### ISSUE TITLE
Can I host Lychee-Laravel with a subpath? Like `https://example.dev/lychee/`

### ISSUE THREAD

**Issue by hq5544** [LycheeOrg/Lychee-Laravel#349]
Can I host Lychee-Laravel with a subpath? Like `https://example.dev/lychee/`

I have tried bellow nginx config on my server, but home page always return 404.

```nginx
# bellow is Lychee-Laravel config, access by https://example.dev/lychee/
location ~ ^/lychee/?(.*)$ {
    root /var/www/lychee/public;

    try_files /$1 /$1/ /index.php?$query_string;

    if (!-e $request_filename) {
        rewrite ^/lychee/?(.*)$ /lychee/index.php?/$1 last;
        break;
    }

    location ~ ^/lychee/?(.*\.php)$ {
        try_files /$1 = 404;
        fastcgi_split_path_info ^/lychee/?(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# bellow is my main blog page, which can access by https://example.dev directly
location / {
    proxy_pass http://127.0.0.1:8888;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_redirect off;
    proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
    proxy_ignore_headers Set-Cookie;
}
```

Did I do anything wrong?

**Comment by hq5544** [comment]
I found solution. It works.

```nginx
location ^~ /lychee {
    alias /var/www/lychee/public;
    index index.php;
    try_files $uri $uri/ @lychee;
    location ~ \.php$ {
        if (!-e $request_filename) {
            rewrite ^/lychee/?(.*)$ /lychee/index.php?/$1 last;
            break;
        }
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }
}
location @lychee {
    rewrite /lychee/(.*)$ /lychee/index.php?/$1 last;
}

```

**Comment by ildyria** [comment]
I'm reopening this issue so it can be added to the Docs.

**Comment by Fireballcz** [comment]
A bit OT, but may be interesting for someone: 
Im successfully hosting the whole L-L outside the htdocs, just with an alias in httpd.conf to it's public folder. Working like a charm :)

**Comment by saikon** [comment]
How can this be done with .htaccess? 

This page tells me to modify config files I do not have access to https://github.com/LycheeOrg/Lychee-Laravel/issues/16

This page gives info about some .htaccess method, but it does not work with Lychee-Laravel
https://serverfault.com/questions/942417/htaccess-change-document-root-to-public-and-prevent-public-from-being-used

```
# Block direct requests to the "public" subdirectory
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule ^public($|/) - [R=404]

# Rewrite all requests that are not already for the "public" subdirectory
RewriteRule !^public/ /public%{REQUEST_URI} [L]
```

I have my web server as follows:
```
website.com
- other stuff
- Lychee-Laravel
-- .htaccess
-- public
-- other lychee stuff
```
I would like to redirect everything from `website.com/Lychee-Laravel` (or any other url like `website.com/pics`) to the public directory this Laravel version seems to require. The old version you could just have in any simple directory you wanted (like that pics one).

**Comment by saikon** [comment]
To answer my own question. A simple symbolic link seems to do the trick. Maybe someone can explain if that is a bad idea or not.

At website.com root `ln -s Lychee-Laravel/public pics` and I get exactly what I want: `website.com/pics`
