### ISSUE TITLE
Diagnostics page fails if open_basedir is set to anything than /

### ISSUE THREAD

**Issue by ABLomas** [LycheeOrg/Lychee-Laravel#351]
Probably in most shared hosting environments open_basedir is limited to few binaries and wwwroot, but Lychee-Laravel fails to display "Diagnostics" page in this case:

Browser gets HTTP/1.1 500 Internal Server Error (displays server error or API not found).
In storage/logs/laravel.log:
```
[2019-09-28 15:13:37] local.ERROR: disk_total_space(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/mnt/sys/www/) {"exception":"[object] (ErrorException(code: 0): disk_total_space(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/mnt/sys/www/) at /mnt/sys/www/website/s/Lychee-Laravel/app/Metadata/DiskUsage.php:93)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'disk_total_spac...', '/mnt/sys/www/we...', 93, Array)
```
I think, disk space usage is not critical for diagnostics (but usefull) and can just return empty string/NULL/0 and still display other information?
Even more, if webroot is on different partition (not "/") this will just give incorrect info. Why not run disk_free_space on dirname(__FILE__, 2); (and this should not fail even with open_basedir included)?

**Comment by ildyria** [comment]
Thank you for bringing this up.

**Comment by ildyria** [comment]
@ABLomas can you check if the branch `fix-351` fixes your problem ? :)

**Comment by ABLomas** [comment]
Diagnostics page works for me without changing server configuration, so at least open_basedir issue is fixed, thanks ;-)
