### ISSUE TITLE
[Enhancement] When copy any photo to another album, can I only remain one unique photo?

### ISSUE THREAD

**Issue by hq5544** [LycheeOrg/Lychee-Laravel#354]
When copy any photo to another album, can I only remain one unique photo?

The latest version, after I copy a photo to another album, there will be two same photo in the recent album. **It confuses me.**

Also, there will be two same file but different name on my disk. **It is a kind of waste.**

Can I only remain one photo, but link them to different album? Like a tag system.

**Comment by ildyria** [comment]
> When copy any photo to another album, can I only remain one unique photo?

Nope, you are doing a *copy* not a *move*.

> The latest version, after I copy a photo to another album, there will be two same photo in the recent album. **It confuses me.**

Of course, you have a *new* photo (from the copy).

> Also, there will be two same file but different name on my disk. **It is a kind of waste.**

No, we handle this properly. You do not have a duplicate on the disk.

> Can I only remain one photo, but link them to different album? Like a tag system.

Smart albums for tags is schedule for later #48
