### ISSUE TITLE
Diagnostic is too slow

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#356]
### Detailed description of the problem

Opening the Diagnostic page should not be that long. This is due to the commit check (request to Github, waiting etc).

### Solutions

- Cache the update check response every *x* days ?
- Remove the update check ?
- Add a link to the front-end to apply update (even if none is available).
- Add button to check for updates ?

**Comment by d7415** [comment]
Maybe do the check as a separate request to the back end, after (or while) the rest of the page is loaded?

**Comment by ildyria** [comment]
It's take waaayyyy to long time to display.

**Comment by ildyria** [comment]
Still not fixed if you have a big number of pictures.
