### ISSUE TITLE
skip_duplicates for Imported Folders?

### ISSUE THREAD

**Issue by avieros** [LycheeOrg/Lychee-Laravel#366]
I'm really enjoying lychee-laravel, but I notice that "skip_duplicates" doesn't apply to imported folders. I'm using google drive as a repository, then using drive to sync those folders/images to my server.

But when I choose "Import from Server" it imports all of the folder structure as Albums again. In my case I have C1/C2/C3/C4 as folders, with subfolders underneath. So even if i do a merge, my subfolders are duplicated.

Is there a simple code change (php etc) that I can do to avoid this? My album structure won't change, so even if I can disable "folder imports" and just import files into the appropriate structure?

thanks!

**Comment by d7415** [comment]
I'll see if I  can find time to look this evening.

**Comment by d7415** [comment]
It seems I hardcoded this in v3 - it wasn't lined to `skip_duplicates` at all. I didn't write the v4 one, but I'll take a look when I get time, unless someone beats me to it. I probably should familiarise myself with that part...

**Comment by avieros** [comment]
> I didn't write the v4 one, but I'll take a look when I get time, unless someone beats me to it. I probably should familiarise myself with that part...

awesome. would it be difficult to import folders on first import, then from each subsequent import only import files (in that folder structure)? maybe via a toggle? or is it now going from bug to enhancement

**Comment by d7415** [comment]
> awesome. would it be difficult to import folders on first import, then from each subsequent import only import files (in that folder structure)? maybe via a toggle? or is it now going from bug to enhancement

My plan would be that, like the v3, if the folders match existing album names (including any parents in this case) it would use them (possibly/probably with a config setting). If the folder tree doesn't match the album tree it would create new ones.

But yes, this is technically an enhancement as this functionality is separate to `skip_duplicates` and has never been in v4.

**Comment by avieros** [comment]
sounds exactly what i'm after. could you tell me where that functionality is coded in V3 (file) so i can have a look?

**Comment by d7415** [comment]
https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Album.php#L28-L34

It's much simpler in v3 because there is no subalbums support.

**Comment by kamil4** [comment]
Why don't you try #368? In my light testing it seemed to work...

**Comment by avieros** [comment]
hi kamil4, tried #368 (manually) - same issue, duplicate folders...

**Comment by avieros** [comment]
is it because my parent folder is "password protected" & "public" , and all subfolders are "public" 
is it ignoring those set flags, and assuming the folders are different?
