### ISSUE TITLE
Why images 'medium' are format jpg but with extencion .png?

### ISSUE THREAD

**Issue by joserick** [LycheeOrg/Lychee-Laravel#375]
Hi,

Why, when I upload a image in format PNG (Photo.png), Lychee create the 'medium' in format jpg but with extension '**.png**'?

With thumbnail this doesn't happen, the thumbnail is format 'jpg' with extension .jpeg.

**Comment by kamil4** [comment]
Are you using GD for image resizing by any chance? (see the value of `Imagick Active` in Diagnostics -- if it's `0`, you are using GD).

I just checked and with Imagick the intermediate files with `.png` extensions are in fact PNGs, but with GD they appear to be JPEGs as you reported, so there's certainly a bug there.

@ildyria, @d7415, what is your opinion on how this _should_ work? Should the intermediate files we generate always be JPEGs (it is the most space and bandwidth efficient format we support, after all) or should they be of the same format as the original?

Our code currently assumes that `small` and `medium` are the same format as the original; curiously though, the square thumbs we generate are always JPEGs. So we aren't exactly consistent one way or the other.

Still, the easiest fix is to change the `GdHandler` to match the behavior of `ImagickHandler`.

**Comment by SerenaButler** [comment]
A png should always be a png as you will e.g. lost transparency when converting to jpg.

**Comment by kamil4** [comment]
> A png should always be a png as you will e.g. lost transparency when converting to jpg.

I was going to respond _"Our background is black so this won't matter"_ but on second thought, that's not correct. It's off-black in the album view and also slightly transparent in photo view. Transparent pngs would render particularly oddly when used as album covers, as we stack three of those on top of each other, so I guess I'm glad that we always use jpegs there...

Still, I think we are in a semi-agreement that it's better to fix the `GdHandler` to match the source format when scaling down...

**Comment by joserick** [comment]
Hi, 
@kamil4 you were in the correct, I was using GD, so I was generating images in jpg format with png extension.

But personally, I would like that by default the small, medium and miniature images are jpg with extermination of jpeg, to reduce broadband and storage.

Already if in the future you implement in the Lychee configuration section, a option to generate the images with the same extension and format as the original, it would give Lychee an extra plus.

**Comment by kamil4** [comment]
> But personally, I would like that by default the small, medium and miniature images are jpg with extermination of jpeg, to reduce broadband and storage.

Sorry, the PR I submitted does the opposite as that behavior matches the rest of the code we have...

But I understand the point you are making. May I suggest that you open a separate, enhancement-type issue, requesting that feature? Mind you, it's unlikely to be a high priority for the team, but we are always open to external contributions :smiley:. We actually already have much of the code to handle it, because that's what we do for the movie files, so it would be a matter of generalizing it, adding a config option, and probably a new column in the `photos` table to indicate if the intermediate sizes inherit the format of the original or are forcibly jpegs...
