### ISSUE TITLE
Live photo

### ISSUE THREAD

**Issue by Aymenel** [LycheeOrg/Lychee-Laravel#378]
Сould you implement view live photo from Apple?

**Comment by kamil4** [comment]
FYI, I moved this issue to the Lychee-Laravel repo so that it doesn't get lost...

Regarding the exiftool support, I just added some comments about it at https://github.com/LycheeOrg/Lychee-Laravel/issues/363#issuecomment-545507833.

**Comment by tmp-hallenser** [comment]
Hi,

I’ve just pushed a first version supporting Live Photos (Apple Live Photos and Google Motion Photos) to my repository (branches support-live-photo)
* Backend: https://github.com/tmp-hallenser/Lychee-Laravel
* Frontend: https://github.com/tmp-hallenser/Lychee-front

When installing it, you need to run npm install && npm run compile in the frontend and composer install in the backend to update files.

Upload:
* Apple Live Photos: Upload jpg and mov after each other
* Google Motion Photos: Normal upload of jpg, video is part of jpg file

Notes:
* High resolution video might challenge the browser
* Package for viewing only supports mov files, hence the current version converts the mp4 file from a Google Motion Photo to mov while keeping codecs, resolution etc. (should be very fast)
* we need exiftool to extract the relevant exif information
* it’s just a first version with likely some room for improvements and bugfixes

File samples:
* Google Motion Photo:
1. https://github.com/joemck/ExtractMotionPhotos/issues/1#issuecomment-397476658 
2. https://photos.google.com/share/AF1QipO2_gTkgT1QwgYaWCTowaN6d2Cb5rvyJU10cjAdSU9Ao8v9Ec-r1v1cKdWEx6PNqg/photo/AF1QipP3IopzoNWtRutf8O0b0V_Tm83GIg_MdgnEWVMA?key=WEdYT3BMNFZGdUlwQ0l6aEdFT1UwVlg2LUZESDhn
* Apple Live Photo:
1. https://developer.apple.com/live-photos/assets/boy.jpg and https://developer.apple.com/live-photos/assets/boy.mov
2. https://developer.apple.com/live-photos/assets/girl.jpg and https://developer.apple.com/live-photos/assets/girl.mov

**Comment by tmp-hallenser** [comment]
I'll close the issue since we have a first version of live photo implemented.

**Comment by jscmidt** [comment]
How do I upload Live Photos? When I upload images via Safari on iPhone, only the JPEG part is uploaded…
