### ISSUE TITLE
[Enhancement] Use the Exif to generate the description of the picture.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#386]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*

When uploading pictures on facebook, if you set up the caption in Lightroom, they are automatically set when you upload. I guess the metadata are recorded in the Jpeg file. It would be nice if the tags and caption from Lightroom could also be imported in Lychee.

**Comment by kamil4** [comment]
We do have the code already to extract description and tags based on IPTC Metadata (see https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Metadata/Extractor.php#L89-L111). I guess it just needs to be expanded to support the format that LR uses?

**Comment by tmp-hallenser** [comment]
Could someone share an example?

**Comment by ildyria** [comment]
My bad, we already do it. :) I just checked with the following picture.
I guess I don't use the Description overlay enough...
![EOSR2616](https://user-images.githubusercontent.com/627094/68530571-a9685f00-0309-11ea-86f4-4cf1572ee667.jpg)

Well this kinda indicate that @SerenaButler need to make a proposition for improving the view. :D
