### ISSUE TITLE
Upgrade problems

### ISSUE THREAD

**Issue by Fireballcz** [LycheeOrg/Lychee-Laravel#388]
Dear friends,
Im using Lychee-Laravel as additional image storage (about 10,000 images now) supporting my new store.
A few days ago I upgraded php to 7.3.11 and 64bit architecture from 32bit. Also Lychee-Laravel to the latest version (manual, by overwriting), including install of the latest ImageMagick and ffmpeg . Everything looked good from the visitors side, until now, when I tried to upload new photos.
I have got an errors in log (missing column imgDirection) and big photos were not uploaded just thumbs and album was empty.
So I cerated a new "photos" table column imgDirection (decimal, 10,4, NULL).
Then all new images were uploaded successfully.
Lychee seems to be working 100%, but Im getting these errors with every single image upload:
**App\Configs::get_value -- 173 -- raw_formats does not exist in config (local) !
App\Configs::get_value -- 173 -- force_32bit_ids does not exist in config (local**) !
Will I run into future problems? If so, any recommenadtion, how to solve this?
Many thanks!

**Comment by ildyria** [comment]
as long as you do `./artisan migrate` you should be fine.
Just double check that in advanced config the keys `raw_formats` and `force_32_bit_ids` are present.

**Comment by Fireballcz** [comment]
Thanks! Solved!!!
