### ISSUE TITLE
/frame shows same starred picture

### ISSUE THREAD

**Issue by RodeBaert** [LycheeOrg/Lychee-Laravel#390]
The / frame option only shows one starred picture and not the other starred pictures.

1. Go to 'https://www.vanveen-nl.com/foto/public/frame'
2. See the result. (every 5 seconds you see the same picture)
If you go to https://www.vanveen-nl.com/foto/public/ you will see all public abums incl. the starred album with 30+ pictures

### Browser and system
Google Chrome
Edge
Lychee is installed on a shared server

**Comment by ildyria** [comment]
Confirmed.

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Http/Controllers/PhotoController.php#L121

**Comment by kamil4** [comment]
Actually, this part works. However, it implies ordering, which prevents `inRandomOrder()` from doing anything.
