### ISSUE TITLE
Not an issue. Q: How to translate to Czech language?

### ISSUE THREAD

**Issue by Fireballcz** [LycheeOrg/Lychee-Laravel#392]
(Laravel implementation)

**Comment by Fireballcz** [comment]
Hello Benoit!
CZ transalation of Lychee-Laravel is finished, up and running! Extension just renamed to go through :)
[Czech.txt](https://github.com/LycheeOrg/Lychee-Laravel/files/3855939/Czech.txt)

**Comment by Fireballcz** [comment]
Oh, I found a few typos, how to fix them? Online on git should be the quicekst way... Im new here, any how to? Sorry...

**Comment by ildyria** [comment]
What you can do, is:

1. fork the repository (via the button).
2. clone it:
```sh
git clone https://github.com/Fireballcz/Lychee-Laravel
```
3. Get in the folder
```sh
cd Lychee-Laravel
```
4. set up your username and email
```sh
git config user.name Fireballcz
git config user.email <your email here>
# this is useful for the commit later.
```
5. Create a new branch
```sh
git checkout -b fix-cz
```
6. edit the file, typos etc...
7. commit your changes:
```sh
# add the changes 
git add app/Locale/
# commit the changes with a message
git commit -m "fix some typos"
```
8. Push your changes
```sh
git push origin fix-cz
```
9. Open a pull request / tell us when you pushed, we will be able to get the changes. :)

Voilaaa

**Comment by Fireballcz** [comment]
Thanks, I forgot - Im on Windows, all my web and also Lychee is at Windows server - I must report Lychee-Laravel's 100% functionality (the latest x64 Apache, php, MariaDB), I think, you should know :) Not just Linux :)
I understand, that I should install some version of git repository. Any good (the best - free) recommendation for Win?

**Comment by Fireballcz** [comment]
I think, this is the shortest way to update my translation. Fixed some typos, added a few variables (source = slovak.php). Working on JUST NOW updated Lychee Laravel...
Is this langfile OK also for Lychee itself or should I compare/re-translate it seprately?
[Czech_fixed.txt](https://github.com/LycheeOrg/Lychee-Laravel/files/3856135/Czech_fixed.txt)

**Comment by ildyria** [comment]
The language file is pretty similar, it is just the header part (see the `namespace Lychee\Locale;` ) which will be different.

**Comment by d7415** [comment]
FYI, if you browse to https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Locale/Czech.php there should be an edit pencil at the top right of the file contents. I'm pretty sure that streamlines the fork/edit/PR process for you.

**Comment by ildyria** [comment]
Fixed anyway. :'D

**Comment by d7415** [comment]
> Fixed anyway. :'D

I saw :)

**Comment by Fireballcz** [comment]
Thanks for the fix. There were a few really stupid typos I was ashamed for...
Also thanks to **d7415** for a good hint!
