### ISSUE TITLE
Unable album zip download

### ISSUE THREAD

**Issue by Fireballcz** [LycheeOrg/Lychee-Laravel#397]
Dear friends,
After L-L upgrade (2019-11-03) to the latest version (4.0.0-beta.1),
Im not able to download zipped album or selected photos.
Im getting just browser response "file not found" - links are like the following
https://www.mydomain.com/album/api/Album::getArchive?albumIDs=1572468403
The download links before and after upgrade are similar.
Lychee, Apache and PHP logs are clean.
Seems to me like a probelm with permissions or so, not sure...
Is there any TEMP location?

Im creating bulletproof backups, when doing upgrades etc.
When I returned back to previous version from backup, everything was worked normally.
But there is many uploads, so I need current version working...
Please any idea?
Many thanks!

P.S.: Running Win10x64, Apache 2.4.41, MariaDB 10.4.8, PHP 7.3.11,

**Comment by Fireballcz** [comment]
Update:
When leaving latest version of Laravel and roll back just "public" folder (uploads untouched) ZIP download stareted to work.
But I have old Lychee containing sorting bug etc :( Unhappy :(

**Comment by ildyria** [comment]
During your upgrade, did you run the migration again ?
`php artisan migrate`

**Comment by Fireballcz** [comment]
Thanks **ildyria** for your response.
Yes I did.
5 minutes ago I found the right solution. My headache is away now.
Needed dependecies fix/update. Fixed by "composer install --no-dev".
Now working like a charm!
Many thanks all you guys for L-L existence, I really like it.

**Comment by ildyria** [comment]
The best way to upgrade is directly to use git instead of the releases. :)
But it is surprising you needed the `composer install` as those files are supposed to be provided by the .zip

**Comment by Fireballcz** [comment]
I remmeber, yes you said this a few weeks ago.
Can you please help with a good (free is the best) git piece of soft for Win?
I saw a few of them, but I can not decide which one :(

**Comment by ildyria** [comment]
Personally, the basic Git BASH was good enough for me: https://git-for-windows.github.io/
As long as you know the git commands (git pull etc...) then you are good to go. :)

**Comment by Fireballcz** [comment]
Many thanks, I'll give them a try :)
