### ISSUE TITLE
has_exiftool not updating in DB

### ISSUE THREAD

**Issue by psjbeisler** [LycheeOrg/Lychee-Laravel#409]
### Steps to reproduce the issue

Clean checkout of #401 ;
With postgreqsl database ;
`artisan migrate` Nothing to migrate. ;
`Error: Wrong property for has_exiftool in database, expected 0 or 1, got `
`has_exiftool:              ` (blank)

### Output of the diagnostics
    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      c08d927 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.4
    PostgreSQL Version:        PostgreSQL 11.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
    
    Lychee total space:        1.90 GB
    Upload folder space:       1.84 GB
    System total space:        48.99 GB
    System free space:         28.89 GB (58%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                bundled (2.1.0 compatible)

### Browser and system
Firefox / Linux

**Comment by tmp-hallenser** [comment]
What does `php artisan migrate:status` say? Did you try to initiate the migration manually?

**Comment by avalx** [comment]
The same happened on my installation. I ran the migration manually and everything looks OK:

`# php artisan migrate
PHP Notice:  date_default_timezone_set(): Timezone ID 'CEST' is invalid in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 49
Migrating: 2019_12_02_2100_config_exiftool
Migrated:  2019_12_02_2100_config_exiftool (0.01 seconds)
Migrating: 2019_12_15_1000_config_check_update_every_cat_fix
Migrated:  2019_12_15_1000_config_check_update_every_cat_fix (0.01 seconds)
`
And status is also fine:

`| Yes  | 2019_12_02_2100_config_exiftool                   | 4     |
| Yes  | 2019_12_15_1000_config_check_update_every_cat_fix | 4     |
+------+---------------------------------------------------+-------+
`
So I changed the value of `has_exiftool` in the database to 1 (is this OK?) and now the error has gone away.

**Comment by psjbeisler** [comment]
```
| Yes  | 2019_10_07_0900_config_map_include_sub_albums     | 3     |
| Yes  | 2019_10_09_233402_config_map_mod                  | 3     |
| Yes  | 2019_10_11_093442_config_check_update_every       | 3     |
| Yes  | 2019_12_02_2100_config_exiftool                   | 3     |
| Yes  | 2019_12_15_1000_config_check_update_every_cat_fix | 3     |
+------+---------------------------------------------------+-------+

```

**Comment by tmp-hallenser** [comment]
It looks to me as if the db migration itself works. Where did you get the error message `Error: Wrong property for has_exiftool in database, expected 0 or 1, got has_exiftool: ` Can you share some more information?

@avalx Are you also using a postgresql db?

**Comment by avalx** [comment]
> It looks to me as if the db migration itself works. Where did you get the error message `Error: Wrong property for has_exiftool in database, expected 0 or 1, got has_exiftool: ` Can you share some more information?
> 
The error was shown when I chose the Settings -> Diagnostics

> @avalx Are you also using a postgresql db?
Sorry I didn't mention - I'm using mysql db.

Now after I changed the value of `has_exiftool` from NULL to 1 in the database, the Diagnostics report looks OK:

`  Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      c08d927 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.3.20-MariaDB
    
    Lychee total space:        470.57 MB
    Upload folder space:       415.04 MB
    System total space:        105.20 GB
    System free space:         86.13 GB (81%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        description
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    1
    image_overlay:             1
    image_overlay_type:        exif
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           1
    Mod_Frame:                 0
    Mod_Frame_refresh:         30
    landing_page_enable:       0
    landing_owner:             Andrej Valencic
    landing_title:             A V
    landing_subtitle:          These are my photos!
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            https://www.flickr.com/JohnSmith
    landing_twitter:           https://www.twitter.com/JohnSmith
    landing_instagram:         https://instagram.com/JohnSmith
    landing_youtube:           https://www.youtube.com/JohnSmith
    landing_background:        dist/cat.jpg
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    site_title:                Lychee v4
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2019
    public_search:             0
    additional_footer_text:    
    display_social_in_gallery: 0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1
    map_display:               0
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              1`

**Comment by psjbeisler** [comment]
confirmed, thanks for the quick fix
