### ISSUE TITLE
Name of the image on import from server

### ISSUE THREAD

**Issue by JacquelinDV** [LycheeOrg/Lychee-Laravel#410]
When I import images from the server (dir ..../public/uploads/import) the image's name (Title field in the photos database table)  is truncated to 32 or less chars when the length of the name of the imported photo is more 

    Lychee server **Diagnostics**
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      6867dd4 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.2
    MySQL Version:             10.1.43-MariaDB-0ubuntu0.18.04.1
    
    Lychee total space:        25.14 GB
    Upload folder space:       24.95 GB
    System total space:        48.60 GB
    System free space:         13.77 GB (28%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1687
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        title
    sorting_Albums_order:      ASC
    imagick:                   1
    skip_duplicates:           1
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      fr
    layout:                    1
    image_overlay:             1
    image_overlay_type:        exif
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 0
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    landing_page_enable:       0
    landing_owner:             jdv
    landing_title:             jdv
    landing_subtitle:          Mon album photo
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            
    landing_twitter:           
    landing_instagram:         
    landing_youtube:           
    landing_background:        dist/cat.jpg
    site_title:                jdv
    site_copyright_enable:     1
    site_copyright_begin:      2009
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            1
    downloadable:              0
    photos_wraparound:Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      6867dd4 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.2
    MySQL Version:             10.1.43-MariaDB-0ubuntu0.18.04.1
    
    Lychee total space:        25.14 GB
    Upload folder space:       24.95 GB
    System total space:        48.60 GB
    System free space:         13.77 GB (28%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1687
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        title
    sorting_Albums_order:      ASC
    imagick:                   1
    skip_duplicates:           1
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      fr
    layout:                    1
    image_overlay:             1
    image_overlay_type:        exif
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 0
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    landing_page_enable:       0
    landing_owner:             jdv
    landing_title:             jdv
    landing_subtitle:          Mon album photo
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            
    landing_twitter:           
    landing_instagram:         
    landing_youtube:           
    landing_background:        dist/cat.jpg
    site_title:                JDV
    site_copyright_enable:     1
    site_copyright_begin:      2009
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            1
    downloadable:              0
    photos_wraparound:         1
    map_display:               0
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3         1jdv
    map_display:               0
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3

**Comment by ildyria** [comment]
More than 30 characters titles... That is VERY long.

**Comment by JacquelinDV** [comment]
In my old imaes i import the image title is like a description!
A1nd I know many  systems using this possibilt until 255 chars.
Merci
