### ISSUE TITLE
`api_key` no longer works.

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee-Laravel#417]
### Detailed description of the problem
Not sure what change affected this, but logging in via a script no longer works due to Laravel's built-in CSRF protection. This is bypassed in the `api` endpoints if the `api_key` exists, but a login and cookie is still required for authentication. Not sure the best way to handle this specifically for the login endpoint.

Commenting out `\App\Http\Middleware\VerifyCsrfToken::class` from `/app/Http/Kernel.php` corrects the issue, but again, probably not how you want to solve the problem.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Make a POST request to the login endpoint via a script (I can provide one if necessary). The server responds with a 419 error code.

**Comment by ildyria** [comment]
> Make a POST request to the login endpoint via a script (I can provide one if necessary). The server responds with a 419 error code.

That would be convenient as I have never used it. :(

**Comment by alex-phillips** [comment]
@ildyria This is what currently allows the CLI I built to work. Until this is fixed, it won't be usable.

**Comment by d7415** [comment]
This seems too easy....

**Comment by d7415** [comment]
@alex-phillips Could you try the `issue_417` branch and see if that works?

**Comment by alex-phillips** [comment]
@d7415 That didn't do it. Still getting `419` error code.

**Comment by d7415** [comment]
Disappointing, but not surprising. I'll keep looking.

**Comment by alex-phillips** [comment]
No problem. Thanks for digging into this!

**Comment by d7415** [comment]
Weird. I haven't managed to login yet, but the API is returning properly for me with that one character fix.

**Comment by alex-phillips** [comment]
@d7415 How are you testing? Maybe I'm doing something differently?

**Comment by d7415** [comment]
`curl -d "a=b" -H "Authorization: abcdef" "http://lycheetest/api/Albums::get"`

**Comment by alex-phillips** [comment]
@d7415 It was an issue in my test code. https://github.com/LycheeOrg/Lychee-Laravel/issues/417 does fix the isssue!

**Comment by d7415** [comment]
:tada:
