### ISSUE TITLE
[Enhancement] unregistered users star photos

### ISSUE THREAD

**Issue by ruslanx80** [LycheeOrg/Lychee-Laravel#422]
Hi all. How to allow unregistered users to star photo. Where in code to edit?
Thank you.

**Comment by ildyria** [comment]
Sorry it took us a long time to get back at you.

Starring photos is not per person. It is a functionality per album for admin/registered user.
While it is possible to disable the security check, this also implies a lot of changes in the front end.
This will not be supported.

For the code to edit you will need to see:
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/routes/web.php (remove the middleware)

https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/lychee.js#L522 (remove the unbind for s)
