### ISSUE TITLE
Album sort label incorrect

### ISSUE THREAD

**Issue by jsaathof** [LycheeOrg/Lychee-Laravel#431]
### Detailed description of the problem
The label for albums is inconsistent with the setting for album sort is set to "Last Take Date" or "First Take Date". When logged in, the correct label is shown (last or first take date). When not logged in the album creation date is shown. The logged in value is correct.

### Steps to reproduce the issue
1. Go to Settings
2. Set "Sort albums by" to "Last Take Date" or "First Take Date"
3. When logged is the date of the album is correct
4. When not logged is the date of the album creation is shown. The sorting is correct however.

Public:
<img width="708" alt="Screenshot 2020-01-25 at 20 18 23" src="https://user-images.githubusercontent.com/864368/73126609-23c58880-3fb5-11ea-8870-ab7b5cfcb6f0.png">

Logged in:
<img width="706" alt="Screenshot 2020-01-25 at 20 18 44" src="https://user-images.githubusercontent.com/864368/73126617-3d66d000-3fb5-11ea-9881-61a16111cca7.png">

### Output of the diagnostics

    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      -
    Lychee Version (git):      0bcde27 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.2
    PostgreSQL Version:        PostgreSQL 9.6.8 on x86_64-suse-linux-gnu, compiled by gcc (SUSE Linux) 7.4.0, 64-bit
    
    Lychee total space:        13.24 GB
    Upload folder space:       13.18 GB
    System total space:        107.98 GB
    System free space:         50.06 GB (46%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1799
    GD Version:                2.2.5

    Config Information
    ------------------
    image_overlay:             0
    site_title:                ********
    site_copyright_begin:      2007
    landing_instagram:         
    landing_youtube:           
    landing_owner:             Jurriaan Saathof
    landing_title:             Jurriaan Saathof
    landing_subtitle:          
    landing_facebook:          
    landing_flickr:            
    landing_twitter:           
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    lang:                      en
    image_overlay_type:        exif
    default_license:           none
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    full_photo:                1
    delete_imported:           1
    Mod_Frame:                 0
    Mod_Frame_refresh:         30000
    compression_quality:       90
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    site_copyright_enable:     1
    additional_footer_text:    
    landing_page_enable:       1
    landing_background:        uploads/big/12fb044cf99851660e10c6edcacf4736.jpg
    layout:                    0
    site_copyright_end:        2020
    sorting_Albums_col:        max_takestamp
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1

Actual version is 4.0.0 beta2:

    [internet]:/srv/www/Lychee-Laravel
    root# git status
    HEAD detached at v4.0.0-beta.2 

### Browser and system

Firefox 72.0.2/Safari 13.0.4/Chrome 79.0.3945.130, MacOS Mojave

**Comment by tmp-hallenser** [comment]
Please give the pull request #432 a try.
