### ISSUE TITLE
Special right-click menu doesn't appear for new users

### ISSUE THREAD

**Issue by OmniTroid** [LycheeOrg/Lychee-Laravel#437]
### Detailed description of the problem
When you create a new user and share an album with them, logging in with the user and attempting to right-click albums and images does not enable the special menu, but the usual one. Also, the divider h1 shows the text "Admin" when logged in with an ordinary user. I guess this should be "Albums"?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create a new user and a new album
2. Share the album with the user
3. Log in with the user and right click the album
4. The ordinary browser context menu shows up instead of the built-in one.

**Screenshots**
![image](https://user-images.githubusercontent.com/14360110/74829349-22b41c80-5311-11ea-96e9-adb648a2c3fe.png)

### Output of the diagnostics
Not applicable

### Browser and system
Chrome 79.0.3945.130 on MacOS 10.15.2

**Comment by ildyria** [comment]
No this is normal. This user does not have the ownership of that Album, so the right click is not available. You can see _sharing_ as a _read_ permission. We do not have the _write_ permission between users implemented (but we are open to PR ;) ).

> Also, the divider h1 shows the text "Admin" when logged in with an ordinary user. I guess this should be "Albums"?

Actually no, this is because the user does not have any albums (yet). The `h1` divider is to show who is the owner of those albums.

**Comment by OmniTroid** [comment]
How can a user download images then?

**Comment by OmniTroid** [comment]
I understand. However, one of the options in the right-click menu is "Download" which displays a handful of different sizes to download. This is a read function, correct? Shouldn't it be available when a user has read access to an album?

**Comment by ildyria** [comment]
> I understand. However, one of the options in the right-click menu is "Download" which displays a handful of different sizes to download. This is a read function, correct? Shouldn't it be available when a user has read access to an album?

That is a bug. :+1:

**Comment by OmniTroid** [comment]
Done: https://github.com/LycheeOrg/Lychee-Laravel/issues/438

**Comment by ildyria** [comment]
Thanks !

**Comment by ildyria** [comment]
Documented.
