### ISSUE TITLE
Update from lychee to lychee-laravel?

### ISSUE THREAD

**Issue by tilllt** [LycheeOrg/Lychee-Laravel#439]
Heyho,

I am running lychee from the linuxserver/lychee docker, which was the first maintained docker I found. I didn't know there is a new version in the making so I imported something around 10-15000 images into lychee. Is there any way to update to lychee-laravel? I'd really want to avoid importing all that stuff again...

Cheers

**Comment by ildyria** [comment]
The process without docker supports the migration pretty well:

Assuming the following tree:
```
/var/
  |- www/
         |- html/
              |- Lychee/
              |- <you are here in html>
```

You can do:
```sh
git clone https://github.com/LycheeOrg/Lychee-Laravel
cd Lychee-Laravel
# apply composer to install dependencies
composer install --no-dev
# move the pictures
mv ../Lychee/uploads/big/* public/uploads/big/
mv ../Lychee/uploads/medium/* public/uploads/medium/
mv ../Lychee/uploads/small/* public/uploads/small/
mv ../Lychee/uploads/thumb/* public/uploads/thumb/
# copy .env
cp .env.example .env
# edit dot env
vim .env
# don't forget [:] [q] to quit ;)
php artisan migrate
# make apache point to the public/ directory and enjoy.
```

**Comment by tilllt** [comment]
So, where is the database migration being done? Since I have my images on persistent storage outside the docker, I guess the database migration would be the only thing I have to do when switching from lychee docker to lychee-laravel docker?

**Comment by ildyria** [comment]
The migration is being done in the `php artisan migrate`:

To be precise:
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/database/migrations/2018_08_15_102039_move_albums.php
and
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/database/migrations/2018_08_15_103716_move_photos.php

**Comment by WWebber** [comment]
ok. nice. 
is there any way to omit "composer install --no-dev" to install on a server w/o ssh?

**Comment by ildyria** [comment]
As soon as we publish a new release with the install module available.

Though you need to have the php function `exec` available on your server.

**Comment by WWebber** [comment]
But if I'm not allowed to install something via exec on the server of the provider, this would be a drawback in comparison to the original version.. there should probably exist also a workaround, like downloading on a different machine and copying to the server..

**Comment by d7415** [comment]
> But if I'm not allowed to install something via exec on the server of the provider, this would be a drawback in comparison to the original version.. there should probably exist also a workaround, like downloading on a different machine and copying to the server..

We can only cater for so many use cases. That said, the `composer` step isn't required with the release zips, and a similar process could be used to run composer locally and then upload the results (the `vendor` folder, iirc) if that was preferable.

I suspect in a similar way the `php artisan key:generate` could be worked around, but I haven't looked into that.

**Comment by ildyria** [comment]
artisan migrate is the problem. 

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 1 mars 2020 à 14:22, à 14:22, Martin Stone <notifications@github.com> a écrit:

**Comment by ildyria** [comment]
`php artisan migrate` is the biggest problem.

**Comment by ildyria** [comment]
I will try to see if we can make it work without having the `exec` requirement.
