### ISSUE TITLE
FAQ out of date

### ISSUE THREAD

**Issue by 4e868df3** [LycheeOrg/Lychee-Laravel#453]
https://github.com/LycheeOrg/Lychee-Laravel/wiki/FAQ#im-importing-a-lot-of-photos-using-import-from-server-and-lychee-times-out-before-its-done

I'm not finding this setting in Lychee-Laravel?

**Comment by d7415** [comment]
Thanks for pointing that out. It was removed when the logic was changed - in recent Lychee-Laravel installations the script limit is per image rather than for the full import, so it should no longer be required.
