### ISSUE TITLE
[Question] Make albums public?

### ISSUE THREAD

**Issue by knokio** [LycheeOrg/Lychee-Laravel#459]
This may sound super silly but I can't seem to find how to make albums or items public?
I've looked in the wiki, etc.

I've looked at album properties but "Public" is non editable. Can you help?

**Comment by ildyria** [comment]
You can't.

Kidding. :laughing: 

![2020-03-27_1920x1080_13:57:24](https://user-images.githubusercontent.com/627094/77758479-5599b080-7033-11ea-95d7-f150f13eb0f1.png)

**Comment by ildyria** [comment]
For the **smart album** `Public`, it references pictures which are public but in a private album, that one you cannot make public (from memory).

**Comment by knokio** [comment]
Geeezz that was so simple. But as a "new user perspective" it's really not obvious 😁 
Thank you very much :D

**Comment by Mettbrot** [comment]
Just came across this with the same question. I don't think it's that obvious 😆 

Thank you!
