### ISSUE TITLE
exiftool error in log

### ISSUE THREAD

**Issue by stanelie** [LycheeOrg/Lychee-Laravel#461]
### Detailed description of the problem
I get the following error message in the log : 
`-- error   -- App\Metadata\Extractor::extract -- 105 -- Given path () to the exiftool binary is invalid`

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'settings'
2. Click on 'show logs'
3. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

    System Information
    ------------------
    Lychee-front Version:      -
    Lychee Version (git):      ac4e129 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.3.22-MariaDB-0+deb10u1
    
    Lychee total space:        2.00 GB
    Upload folder space:       2.00 GB
    System total space:        58.45 GB
    System free space:         13.67 GB (23%)
    
    Imagick:                   -
    Imagick Active:            1
    Imagick Version:           -
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        max_takestamp
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    1
    image_overlay:             1
    image_overlay_type:        takedate
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 1
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  1
    medium_2x:                 1
    landing_page_enable:       1
    landing_owner:             xxxx xxxx
    landing_title:             photo.xxxxxxx.com
    landing_subtitle:          
    landing_facebook:          
    landing_flickr:            
    landing_twitter:           
    landing_instagram:         https://instagram.com/xxxxxx
    landing_youtube:           
    landing_background:        dist/simone.jpg
    site_title:                Lychee v4
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    SL_enable:                 0
    SL_for_admin:              0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1
    map_display:               0
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              1
    share_button_visible:      0
    import_via_symlink:        0
    has_ffmpeg:                1`

I'm not sure how/where to set this path for the exiftool binary. Also, the "advanced settings" has a "has_exiftool" setting. Am I supposed to change the 0 to a 1 myself if I have exiftool installed?

**Comment by tmp-hallenser** [comment]
`has_exiftool`is the switch to use exiftool. A couple of quick questions:
* Are you on the latest version?
* What do the following commands result in?
1. `which exiftool`
2. `command -v exiftool`
3. `exiftool someRandomPicture.jpg`(replace path with an existing file)

**Comment by ildyria** [comment]
> * Are you on the latest version?

ac4e129 > thus yes.

However I think that his https://github.com/LycheeOrg/php-exif is not up to date.
Which should be solved by `composer install --no-dev`

**Comment by stanelie** [comment]
The output of `which exiftool` is
`/usr/bin/exiftool`
`command -v exiftool` gives the same answer.
`exiftool someRandomPicture.jpg` works and prints out all the exif info.

I am not seeing the error anymore in the log. I did restart Apache at some point after installing the exiftool package. Maybe that fixed it? How can I test that it works with Lychee now?

**Comment by ildyria** [comment]
> How can I test that it works with Lychee now?

Just upload an image. :)

**Comment by stanelie** [comment]
Ok, I did that and no errors in the log, I guess it is fixed.
Thanks and sorry for wasting your time.

Sidenote : how can I purge the log?

**Comment by ildyria** [comment]
> Thanks and sorry for wasting your time.

No problem. :) You are not wasting our time as your question maybe useful to someone else in the future.

> Sidenote : how can I purge the log?

Just empty the Log table. It would be indeed a good idea to add a command for that.

**Comment by stanelie** [comment]
Awesome. Thanks!

**Comment by jlpoolen** [comment]
A Cautionary Tale for User in Gentoo Linux

In Gentoo Linux, I had the **exif** USE flag enacted for my PHP.  One might conclude that was sufficient.  However, activation of the **exif** flag is not enough.  The log (through the Admin account, left pane "Show Logs", reported by attempt of uploading a JPEG file with EXIF failed with:

     2022-05-14 22:26:24 -- error   -- App\Metadata\Extractor::extract -- 172 -- Given path () to the exiftool binary is invalid

In a console on the server, "which exiftool" came back "not found".  So I check with "eix" what there was for "exif" and I installed an exiftool with:

      emerge media-libs/exiftool
      
And then confirmed using the assay above in https://github.com/LycheeOrg/Lychee/issues/461#issuecomment-605411181

      # which exiftool
      /usr/bin/exiftool
      #

And then I uploaded a JPEG with EXIF and was successful.  And there was no need to restart Apache.

**Comment by jlpoolen** [comment]
https://forums.gentoo.org/viewtopic-p-8708621.html#8708621

**Comment by lbonnefond** [comment]
Hello,

I have the same issue, but in may case the explanation is simple: exiftool is not installed (and since I'm using a shared host I can't install it myself). I'm using PHP 8.2 with exif extension though.

My question is: is there a way to make Lychee work without exiftool ? (it's written in the installation instructions that Exiftool is optional)

**Comment by lbonnefond** [comment]
I found the answer : I had to change the has_exiftool value in the database configs table to 0.
It was set to 1 probably because my previous host had exiftool installed...
Sorry for the trouble
