### ISSUE TITLE
Automatic installation to virtual server without SSH access

### ISSUE THREAD

**Issue by ravolar** [LycheeOrg/Lychee-Laravel#463]
Hello
Could,you help, how to run installer for Lychee-Laravel on virtual server if there is no SSH?
Oк how update from V3 to V4 on the same server? Thanks in advance!

**Comment by ildyria** [comment]
Hi, I assume you have a command line etc still on your current machine?

Thus you can do locally:
```
git clone git@github.com:LycheeOrg/Lychee-Laravel
cd Lychee-Laravel
composer install --no-dev
```
You can then transfer the full folder (with the vendor files) to Your virtual server.

Upon accessing it you will be redirected to a `public/` folder which will redirect you to `public/install` and this will allow you to access the install procedure.

Ideally before doing the install procedure, you want to copy the files from the `upload` folder in Lychee v3 to the `public/upload` folder in Lychee v4.

Ideally once this last PR is merged (@d7415 ??) we will pack a release version which basically will contain the first step (`composer install --no-dev`)
