### ISSUE TITLE
Unable to import any photos after latest git pull / composer install

### ISSUE THREAD

**Issue by gardiol** [LycheeOrg/Lychee-Laravel#468]
Tried both via server import and via upload from local pc...

The 
I see this in my browser console:
Error: Something went wrong, error42S22, please check the logs

`{…}
description: "Caricamento fallito. Il server ha restituito un errore!"
params: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
response: "Error: Something went wrong, error42S22, please check the logs"
__proto__: Object { … }
main.js:3996:3
lychee.error https://photos.gardiol.org/dist/main.js:3996:3
process/xhr.onload https://photos.gardiol.org/dist/main.js:7882:27`

but nothing appears in my logs AT ALL. 
either i am missing something, or my logging is not working at all on my installation?

To clarify, albums are created... But images are uploaded... the processing phase aborts with this error. I recently (as in right before doing this upload...) did the git pull / composer install upgrade procedure. This is Lychee Laravel of course.

**Comment by gardiol** [comment]
Here is my diagnostic:
`
 Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      dc5f03a (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.4
    MySQL Version:             10.2.29-MariaDB-log
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1801
    GD Version:                bundled (2.1.0 compatible)
    
    Lychee total space:        228.20 MB
    Upload folder space:       43.00 B
    System total space:        411.20 GB
    System free space:         17.84 GB (4%)

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         0
    sorting_Photos_col:        title
    sorting_Photos_order:      ASC
    sorting_Albums_col:        title
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      it
    layout:                    1
    image_overlay:             1
    image_overlay_type:        desc
    default_license:           reserved
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 1
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  1
    medium_2x:                 1
    landing_page_enable:       1
    landing_owner:             Willy Gardiol
    landing_title:             Willy Gardiol Photos
    landing_subtitle:          Foto di Willy Gardiol
 landing_facebook:          
    landing_flickr:            
    landing_twitter:           
    landing_instagram:         
    landing_youtube:           
    landing_background:        dist/cat.jpg
    site_title:                Willy Gardiol Photos
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1
    map_display:               1
    zip64:                     1
    map_display_public:        1
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              0
    share_button_visible:      0
    has_ffmpeg:                0
    import_via_symlink:        0`

**Comment by ildyria** [comment]
Hummm...

**Comment by ildyria** [comment]
Do you know what was the previous version before the `git pull` ?

**Comment by ildyria** [comment]
Also this looks a pretty weird error to me. :confused:

**Comment by gardiol** [comment]
I managed to get some logs. I had to manually empty the "log" table from the database first, this is the result of importing two pictures:

```
(1, 'notice', 'App\\Metadata\\Extractor::extract', 140, 'Takestamp (1970-01-01 00:00:00) out of bounds (needs to be between 1970-01-01 00:00:01 and 2038-01-19 03:14:07)', '2020-04-08 16:53:58', '2020-04-08 16:53:58'),
(2, 'error', 'App\\Configs::get_value', 173, 'location_decoding does not exist in config (local) !', '2020-04-08 16:53:58', '2020-04-08 16:53:58'),
(3, 'error', 'App\\ModelFunctions\\PhotoFunctions::save', 693, 'Something went wrong, error 42S22, SQLSTATE[42S22]: Column not found: 1054 Unknown column \'location\' in \'field list\' (SQL: insert into `photos` (`id`, `checksum`, `thumbUrl`, `thumb2x`, `medium`, `medium2x`, `small`, `small2x`, `livePhotoUrl`, `livePhotoChecksum`, `type`, `title`, `url`, `description`, `tags`, `width`, `height`, `size`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `takestamp`, `latitude`, `longitude`, `altitude`, `imgDirection`, `location`, `livePhotoContentID`, `public`, `star`, `album_id`, `owner_id`, `updated_at`, `created_at`) values (15863720380381, 9c1c34eb8791ec088748843cbab67af60a08f912, 11288867361296a9cabed384fe1cd1d2.jpeg, 1, 720x1080, 1440x2160, 240x360, 480x720, ?, ?, image/jpeg, PICT0570, 11288867361296a9cabed384fe1cd1d2.jpg, , , 3760, 5640, 5.3 MB, 100, f/2.8, Rollei, PDF-S 340, , 1/60 s, 0 mm, ?, ?, ?, ?, ?, ?, ?, 0, 0, 15863698465234, 0, 2020-04-08 18:53:58, 2020-04-08 18:53:58))', '2020-04-08 16:53:58', '2020-04-08 16:53:58'),
(4, 'notice', 'App\\Metadata\\Extractor::extract', 140, 'Takestamp (1970-01-01 00:00:00) out of bounds (needs to be between 1970-01-01 00:00:01 and 2038-01-19 03:14:07)', '2020-04-08 16:54:06', '2020-04-08 16:54:06'),
(5, 'error', 'App\\Configs::get_value', 173, 'location_decoding does not exist in config (local) !', '2020-04-08 16:54:06', '2020-04-08 16:54:06'),
(6, 'error', 'App\\ModelFunctions\\PhotoFunctions::save', 693, 'Something went wrong, error 42S22, SQLSTATE[42S22]: Column not found: 1054 Unknown column \'location\' in \'field list\' (SQL: insert into `photos` (`id`, `checksum`, `thumbUrl`, `thumb2x`, `medium`, `medium2x`, `small`, `small2x`, `livePhotoUrl`, `livePhotoChecksum`, `type`, `title`, `url`, `description`, `tags`, `width`, `height`, `size`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `takestamp`, `latitude`, `longitude`, `altitude`, `imgDirection`, `location`, `livePhotoContentID`, `public`, `star`, `album_id`, `owner_id`, `updated_at`, `created_at`) values (15863720466194, dd5958731fa6566a33e62b18644412d2f55f3fdb, 5ead3b73ab8b5a75f24e62603e78fc48.jpeg, 1, 720x1080, 1440x2160, 240x360, 480x720, ?, ?, image/jpeg, PICT0566, 5ead3b73ab8b5a75f24e62603e78fc48.jpg, , , 3760, 5640, 5.8 MB, 200, f/2.8, Rollei, PDF-S 340, , 1/30 s, 0 mm, ?, ?, ?, ?, ?, ?, ?, 0, 0, 15863698465234, 0, 2020-04-08 18:54:06, 2020-04-08 18:54:06))', '2020-04-08 16:54:06', '2020-04-08 16:54:06'),
(7, 'notice', 'App\\Metadata\\Extractor::extract', 140, 'Takestamp (1970-01-01 00:00:00) out of bounds (needs to be between 1970-01-01 00:00:01 and 2038-01-19 03:14:07)', '2020-04-08 16:54:11', '2020-04-08 16:54:11'),
(8, 'error', 'App\\Configs::get_value', 173, 'location_decoding does not exist in config (local) !', '2020-04-08 16:54:11', '2020-04-08 16:54:11'),
(9, 'error', 'App\\ModelFunctions\\PhotoFunctions::save', 693, 'Something went wrong, error 42S22, SQLSTATE[42S22]: Column not found: 1054 Unknown column \'location\' in \'field list\' (SQL: insert into `photos` (`id`, `checksum`, `thumbUrl`, `thumb2x`, `medium`, `medium2x`, `small`, `small2x`, `livePhotoUrl`, `livePhotoChecksum`, `type`, `title`, `url`, `description`, `tags`, `width`, `height`, `size`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `takestamp`, `latitude`, `longitude`, `altitude`, `imgDirection`, `location`, `livePhotoContentID`, `public`, `star`, `album_id`, `owner_id`, `updated_at`, `created_at`) values (15863720512462, c30d32ae93c02c6220efde9b8f76dc241ae4b17d, 3bb43e0419c98fee7f02cd9b8f4b5e3c.jpeg, 1, 1424x1080, 2847x2160, 475x360, 949x720, ?, ?, image/jpeg, PICT0561, 3bb43e0419c98fee7f02cd9b8f4b5e3c.jpg, , , 3761, 2853, 3.1 MB, 400, f/2.8, Rollei, PDF-S 340, , 1/30 s, 0 mm, ?, ?, ?, ?, ?, ?, ?, 0, 0, 15863698465234, 0, 2020-04-08 18:54:11, 2020-04-08 18:54:11))', '2020-04-08 16:54:11', '2020-04-08 16:54:11'),
(10, 'notice', 'App\\Metadata\\Extractor::extract', 140, 'Takestamp (1970-01-01 00:00:00) out of bounds (needs to be between 1970-01-01 00:00:01 and 2038-01-19 03:14:07)', '2020-04-08 16:54:24', '2020-04-08 16:54:24'),
(11, 'error', 'App\\Configs::get_value', 173, 'location_decoding does not exist in config (local) !', '2020-04-08 16:54:24', '2020-04-08 16:54:24'),
(12, 'error', 'App\\ModelFunctions\\PhotoFunctions::save', 693, 'Something went wrong, error 42S22, SQLSTATE[42S22]: Column not found: 1054 Unknown column \'location\' in \'field list\' (SQL: insert into `photos` (`id`, `checksum`, `thumbUrl`, `thumb2x`, `medium`, `medium2x`, `small`, `small2x`, `livePhotoUrl`, `livePhotoChecksum`, `type`, `title`, `url`, `description`, `tags`, `width`, `height`, `size`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `takestamp`, `latitude`, `longitude`, `altitude`, `imgDirection`, `location`, `livePhotoContentID`, `public`, `star`, `album_id`, `owner_id`, `updated_at`, `created_at`) values (15863720643358, 9c76c574b13500c710fe4bc4633b376491f80c59, 9facf3de3da5f0e2e7eff66b74182f4c.jpeg, 1, 1620x1080, 3240x2160, 540x360, 1080x720, ?, ?, image/jpeg, PICT0559, 9facf3de3da5f0e2e7eff66b74182f4c.jpg, , , 5640, 3760, 6.7 MB, 400, f/2.8, Rollei, PDF-S 340, , 1/30 s, 0 mm, ?, ?, ?, ?, ?, ?, ?, 0, 0, 15863698465234, 0, 2020-04-08 18:54:24, 2020-04-08 18:54:24))', '2020-04-08 16:54:24', '2020-04-08 16:54:24');
```

--

**Comment by ildyria** [comment]
please do `php artisan migrate` :)

**Comment by gardiol** [comment]
These are B/W pictures i take on film then scan using a film scanner.. So all the usual JPG metadata are surely missing/messed up....

**Comment by ildyria** [comment]
> These are B/W pictures i take on film then scan using a film scanner.. So all the usual JPG metadata are surely missing/messed up....

Nah that should not be a problem.

**Comment by gardiol** [comment]
Yes! artisan migrate fixed it... Sorry, going to add that step too to my update script... Thank you

**Comment by ildyria** [comment]
No problem. :+1:

**Comment by ildyria** [comment]
Glad we could help and solve your problem quickly.

**Comment by gardiol** [comment]
Any more steps i should ensure when updating? I love lychee and i like to be on the cutting edge ...

**Comment by ildyria** [comment]
nah.
basically `git pull ; composer install; php artisan migrate` is what is needed.

**Comment by ildyria** [comment]
The `composer install` is actually less necessary than usual: only when we update the dependencies.
While `php artisan migrate` is way more frequent as this is taking care of the database update.

**Comment by gardiol** [comment]
Thank you again. Solved.

**Comment by ildyria** [comment]
This also why we added a button in the UI so you can do the updates directly online.

You can see here the process done:
`ApplyUpdateFunctions::apply()` is called from:
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/ControllerFunctions/ApplyUpdateFunctions.php

**Comment by avalx** [comment]
> This also why we added a button in the UI so you can do the updates directly online.
> 
> You can see here the process done:
> `ApplyUpdateFunctions::apply()` is called from:
> https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/ControllerFunctions/ApplyUpdateFunctions.php

Just wondering where is the mentioned button in the UI - I can't find it anywhere?

**Comment by ildyria** [comment]
@avalx I updated the wiki to answer your question: 
https://github.com/LycheeOrg/Lychee-Laravel/wiki/Update#update-directly-via-the-gui
:smiley:

**Comment by avalx** [comment]
Well, I still don't see the button 

What I did was (I'm running Fedora 31/Apache):
chown -R apache:apache Lychee/ 
systemctl  restart httpd

Anything else I shoud do?

![Lychee v4 - Diagnostics 2020-04-09 13 06 37](https://user-images.githubusercontent.com/22810741/78889170-761a2f80-7a63-11ea-914d-9b9232f81028.jpg)

**Comment by ildyria** [comment]
Hummm...

Check that `exec` is available and check that `'allow_online_git_pull'` setting is set to `'1'`

```php
		$update &= Configs::get_value('allow_online_git_pull', '0') == '1';
		$update &= function_exists('exec');
```

**Comment by avalx** [comment]
Right, the 'allow_online_git_pull' was '0 and setting it to '1'  did the trick - now I see the update button.
Thanks!

**Comment by ildyria** [comment]
We probably will need to refactor this and at least make it more explicit why the update button is not showing up in the GUI

**Comment by ildyria** [comment]
Also to be noted, you can apply an update just by going to https://example.com/Update  :) If you have granted the correct permissions obviously (and logged as admin).
