### ISSUE TITLE
Login timeout? [Enhancement]

### ISSUE THREAD

**Issue by gardiol** [LycheeOrg/Lychee-Laravel#470]
Can it be changed? I find it very annoyingly short... and every time you are logged out by timeout you don't realize it until you try to call an API. Which might result in aborting import for example :)

Maybe a timeout in javascript that notify that session has expired... or a customizable timeout value?

**Comment by ildyria** [comment]
You can edit your `.env` and modify the `SESSION_LIFETIME=120` part (in minutes).

Hopefully this should allow your session to last longer (not tested).
