### ISSUE TITLE
How to allow public to use tag search function?

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#49]
From : https://github.com/electerious/Lychee/issues/738

> I have tagged various photos with descriptive labels. I'd like public users to be able to search on tags and / or photo titles to find relevant images as other gallery systems allow. Unless the user is logged in the search box is invisible.

**Comment by scratcher28** [comment]
I suggest implementing it with teamtnt/tntsearch.

**Comment by scratcher28** [comment]
No deps, no need to run full reindex, check docs.
I definitely will use it in my fork.

**Comment by copperschnack** [comment]
OK, let's see. I just created my first pull request above.

**Comment by ildyria** [comment]
Hi, thank you for your PR on Lychee-front and Lychee.
Can you also port it for the current repository (aka this one) ? :)
If you need help feel free to drop by on the gitter (https://gitter.im/LycheeOrg/Lobby) and ping either me or @d7415 or @kamil4  :+1:

**Comment by ildyria** [comment]
Fixed.
