### ISSUE TITLE
404 on php/index.php after fresh install

### ISSUE THREAD

**Issue by Hagenzone** [LycheeOrg/Lychee-Laravel#52]
### Detailed description of the problem
Getting a ``"Server error or API not found."`` after fresh installation. Reason seems to be a missing index.php file in (also missing) php folder (see screenshot)

![lychee_404_error](https://user-images.githubusercontent.com/17743230/52165262-941d2f00-26fe-11e9-8f60-11d77ea526b1.PNG)

### Steps to reproduce the issue
* Used this manual to install on server: https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install
* Everything worked out, DB is set up, no errors.
* Set public folder to web root.
* Called website, got 404 when trying to call /php/index.php + ``"Server error or API not found."`` (see screenshot)
* php folder is not present in public folder (should it be?)

### Browser and system
server runs with nginx 1.14.1, php 7.1.24, php-fpm 

Could this be a problem with the missing .htaccess on nginx? What I tried here is to convert the rewrite rules to nginx config as follows (without success):
``````
location / {
        if (!-e $request_filename){
                rewrite ^(.*)$ /%1 redirect;
        }
        if (!-e $request_filename){
                rewrite ^(.*)$ /index.php break;
        }
    }

``````

**Comment by ildyria** [comment]
No, it is totally normal that there is no `php` folder or `php/index.php` file.
This is taken care of by the routes in Laravel. Cf in [routes/web.php](https://github.com/LycheeOrg/Lychee-Laravel/blob/master/routes/web.php):
```php
Route::post('/php/index.php',                   'SessionController@init'); // entry point if options are not initialized
```

To solve this, from https://www.digitalocean.com/community/tutorials/how-to-deploy-a-laravel-application-with-nginx-on-ubuntu-16-04 They just do :
```
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
```

However this approach might be better: https://gist.github.com/ashleydw/afd389b1e763d3c1cf1f
The part that is of interest for you:
```nginx
    # serve static files directly
	location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
		access_log off;
		expires max;
		log_not_found off;
	}

	# removes trailing slashes (prevents SEO duplicate content issues)
	if (!-d $request_filename)
	{
		rewrite ^/(.+)/$ /$1 permanent;
	}

	# enforce NO www
	if ($host ~* ^www\.(.*))
	{
		set $host_without_www $1;
		rewrite ^/(.*)$ $scheme://$host_without_www/$1 permanent;
	}

	# unless the request is for a valid file (image, js, css, etc.), send to bootstrap
	if (!-e $request_filename)
	{
		rewrite ^/(.*)$ /index.php?/$1 last;
		break;
	}

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
```

If you get something to work please do tell us as we don't use nginx and that would be useful for other users.

**Comment by Hagenzone** [comment]
Thanks for your proposals. Just gave it a quick try but neither of the two proposals seem to work (first solution made no difference, second gave me a 502 Bad Gateway). I will take a look at how to integrate laravel in the nginx environment and have some experiments tomorrow and let you know my progress.

**Comment by ildyria** [comment]
The 502 Bad Gateway is actually a good news! It means that the problem is not with the rewrite anymore but with the server parameters.

**Comment by Hagenzone** [comment]
Nice - got it working. Problem yesterday was the _# enforce NO www_ as I already do this before (and that I was short on time ;) ). Shortly - if you already rewrite www to non-www just use this in your server section:
``````
	location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
		access_log off;
		expires max;
		log_not_found off;
	}

	# removes trailing slashes (prevents SEO duplicate content issues)
	if (!-d $request_filename)
	{
		rewrite ^/(.+)/$ /$1 permanent;
	}

	# unless the request is for a valid file (image, js, css, etc.), send to bootstrap
	if (!-e $request_filename)
	{
		rewrite ^/(.*)$ /index.php?/$1 last;
		break;
	}

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
``````
... and optionally get rid of the .htaccess in public folder.

Thanks for the support!

**Comment by ildyria** [comment]
@Hagenzone Can you write a page in the Wiki to descripe how to install Lychee-Laravel on nginx ? :)

**Comment by Hagenzone** [comment]
Sure. Could you grant me access?

**Comment by Hagenzone** [comment]
Does this take a while to apply? Still can't push :(

**Comment by ildyria** [comment]
That is surprising because I untick the box as required:

> - [ ] **Restrict editing to users in teams with push access only**
Public wikis will still be readable by everyone.

**Comment by Hagenzone** [comment]
Tried to edit wiki page locally and push. Resulted in 403. Updated the page via github GUI now.

**Comment by ildyria** [comment]
@Hagenzone perfect. Can we close this issue ? :)

**Comment by Hagenzone** [comment]
Sure, thanks again!
