### ISSUE TITLE
Migrating Lychee -> Lychee-Laravel : id problems

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#56]
Current migration has troubles with converting the id from the v3 to the v4.

There is also a risk of duplicates.

**Comment by ildyria** [comment]
Fixed with last commit.

**Comment by digitalkram** [comment]
I am somehow unable to find any information on how to do the v3 to v4 migration? Nothing in issues, Readme etc. Only some indication that it seems to be possible just like here... Any hint, please?

**Comment by d7415** [comment]
Try [this](https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install).

Please don't use existing (especially closed) issues to ask unrelated questions. If there isn't a matching issue, please create a new one.

**Comment by digitalkram** [comment]
Thank you for the pointer(s). I would not call this unrelated but I get your point. Will do so in future. I skipped installation page as I wanted to find migration information first, did not expect to have it combined. However it makes sense.
