### ISSUE TITLE
Error on migration

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-Laravel#61]
Starting with a fresh v4 installation, trying to migrate from an old Lychee database. The following error returns on the _first_ `artisan migrate` command:

```
Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_username_unique`(`username`))
```

Current lychee install is v 3.2.11
DB: `update_030211`

**Comment by d7415** [comment]
Out of curiosity, which MySQL/MariaDB version are you using?

**Comment by bennettscience** [comment]
Here's my `STATUS` dump:

```
MariaDB [(none)]> status;
--------------
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2

Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server:			MariaDB
Server version:		10.1.37-MariaDB-0+deb9u1 Raspbian 9.0
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
```

**Comment by jgbellin** [comment]
try to edit the /config/database.php file :
at line 50,
repace `'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',`
with `'charset' => 'utf8',
       'collation' => 'utf8_unicode_ci',`
it should work (worked for me)

**Comment by ildyria** [comment]
@jgbellin but you are losing the multi byte version of `utf8mb4` which add emojies and cover additional characters: https://stackoverflow.com/a/30074553/3981163
Might be useful for the `cn` people...

**Comment by bennettscience** [comment]
Ok, finally looping back to this. I removed all Laravel directories and tables. Short of rebuilding the server, I was starting from a blank slate. Running `php artisan migrate` continues to throw the key error.

```
In Connection.php line 664:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_username_unique`(`username`))
```
