### ISSUE TITLE
Localization - some glitches

### ISSUE THREAD

**Issue by uwealtmann** [LycheeOrg/Lychee-Laravel#7]
First of all: Thanks for the lightspeed implementation of the localization feature!
Doing german localization I found some glitches in Implementation:

1. On the main/start page, the word "Albums" at the top center of the page stays unlocalized. Exactly that word was the reason for the issue, because my customer asked me to change this :-)
It may use the 'ALBUMS' variable too.

2. On the "Settings" page, the whole part to change the localization is not localizable :-))

**Comment by uwealtmann** [comment]
Great! But I can't find any documentation about usage. Just replace Lychee with Lychee-Laravel files on the web server? Will it keep all the photos etc.? Sorry - I'm really not a geek ;-)

**Comment by ildyria** [comment]
Moving from Lychee to Lychee-Laravel has not been documented yet. It's on the todo list. 

On the top of my head if you want to give a try :

git clone ---recurse... (You need Lychee-front)
cd Lychee-Laravel
cp .env.example .env
# Edit .env to fit your settings (database...)
./composer install
./artisan migrate

Then you just need to move your upload folder in public/upload 

The migration should take care of moving your database.

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 29 déc. 2018 à 14:45, à 14:45, uwealtmann <notifications@github.com> a écrit:

**Comment by uwealtmann** [comment]
Hi Benoît
Had a look on it. 
You don't use a "$dbTablePrefix =" in your .env file so I can't test it in my environment :-(
And...I don't have root access to it, so 
```
./composer install 
./artisan migrate
```
is impossible to me. Sorry. But with the change I sent (over the hollidays I took some time to read about pull requests) all is fine :-)

**Comment by ildyria** [comment]
Noted. Will add this soon. 

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 29 déc. 2018 à 18:06, à 18:06, uwealtmann <notifications@github.com> a écrit:

**Comment by ildyria** [comment]
@uwealtmann updated see last commit.

**Comment by ildyria** [comment]
Fixed with last commit.
