### ISSUE TITLE
Undocumented need for PDO extension

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#76]
Following the installation instructions, I ran the following:
`$ composer install --no-dev`
This failed with:
```Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal v2.9.1 -> satisfiable by doctrine/dbal[v2.9.1].
    - doctrine/dbal v2.9.1 requires ext-pdo * -> the requested PHP extension pdo is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/cli-php7.2/php.ini
    - /etc/php/cli-php7.2/ext-active/imagick.ini
    - /etc/php/cli-php7.2/ext-active/opcache.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```
I'm running Gentoo Linux, php 7.2.14. The pdo extension wasn't enabled by default. It's not a big deal, I enabled it just as I had to enable curl, exif, gd, mysqli, and zip. It's just that the need for pdo extension to be enabled isn't documented on the Installation page.

**Comment by ildyria** [comment]
Thanks for pointing that one out, I guess I had it enabled by default because I never saw that one.

**Comment by ildyria** [comment]
Did you modify the config to make it need `pdo` because I don't remember this requirement.

**Comment by d7415** [comment]
> Did you modify the config to make it need `pdo` because I don't remember this requirement.

https://github.com/LycheeOrg/Lychee-Laravel/blob/master/composer.lock#L258
Also L3820 and 4854

**Comment by d7415** [comment]
The first is required by Lychee, the second by Laravel-framework and the last is (eventually) required by phpunit, which seems to be required by everything.

This reminds me why I hate this type of package management....

**Comment by ildyria** [comment]
Fixed.
