### ISSUE TITLE
php artisan migrate fails

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#77]
I'm trying to set up Lychee-Laravel following the installation instructions. When running:
`$ php artisan migrate`
I get the following error:
```In Connection.php line 664:

  could not find driver (SQL: select * from information_schema.tables where t
  able_schema = homestead and table_name = migrations)


In PDOConnection.php line 31:

  could not find driver


In PDOConnection.php line 27:

  could not find driver
```
Is it failing because I'm not trying to migrate an old Lychee database but instead I'm trying to create a new instance from scratch? Should I be using a different command than "migrate"? Or do I have to start with an old Lychee database for now?

**Comment by ildyria** [comment]
Both should work: Migrating from an old sql instance or creating a new version. 
The process is the same: `php artisan migrate`

**Comment by d7415** [comment]
Missing driver looks to me like Gentoo is missing something else that we're taking for granted. As it's in the PDO part it's probably linked to #76.

**Comment by kamil4** [comment]
Thanks for your help! Indeed this looks like a Gentoo-specific issue. I enabled mysqli and pdo but apparently I also needed to enable mysql. There's a discussion about this at the link below, indicating that the current undesirable behavior is for historical reasons:
[https://bugs.gentoo.org/481190](url)
Anyway, the error message from php artisan migrate changed to:
```In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [1049] Unknown database 'homestead' (SQL: select * from inf  
  ormation_schema.tables where table_schema = homestead and table_name = migr  
  ations)                                                                      
                                                                               

In PDOConnection.php line 31:
                                                       
  SQLSTATE[HY000] [1049] Unknown database 'homestead'  
                                                       

In PDOConnection.php line 27:
                                                       
  SQLSTATE[HY000] [1049] Unknown database 'homestead'  
```
I fixed it by creating the said (empty) database manually through the mysql console but it wasn't obvious to me if that was how it was supposed to be? Anyway, I'm now up an running on Lychee-Laravel so my future developments will be against this new version. Thank you!

**Comment by ildyria** [comment]
I updated the documentation to reflect that and also provided an CLI copy paste steps for Debian. This should make it smoother to install now.
