### ISSUE TITLE
If Landingpage -> Back-Button on Albums Page

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#86]
If Landingpage is activated a Back Button on the Albums Page is needed to go back to Landingpage.

**Comment by ildyria** [comment]
I'm not in favor of changing the login button for an hamburger one. An hamburger is a bit of an overkill for 2 buttons (login & back). I would be more happy with "click on the title = back".

**Comment by SerenaButler** [comment]
I had the future possible menus in mind for the hamburger. The Back Button might be named "Home" though. But with all these changes (Landing Page, Contact, Imprint, Portfolio etc.) I think the IA should be redefind. I also suggest a footer ;-)

**Comment by ildyria** [comment]
IA ?

**Comment by SerenaButler** [comment]
Information Architecture

**Comment by ildyria** [comment]
I read "Intelligence Artificielle" :laughing:

**Comment by SerenaButler** [comment]
ROTFL .... :-D

**Comment by ildyria** [comment]
if you click on the "Albums" bar, then you will be going back to the landing page (if enabled).

**Comment by SerenaButler** [comment]
I don't like it that way, bad UX. But ok for the moment.

**Comment by SerenaButler** [comment]
At least give the header__title -> cursor: pointer; ;-)

**Comment by ildyria** [comment]
Make me a burger. :smile:

**Comment by SerenaButler** [comment]
Haha ... I will ;-)
