### ISSUE TITLE
Migration Lychee 3 -> 4 // Album Creations dates not migrated but overwritten

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#89]
All Album Dates now February 2019 ... :-(

![image](https://user-images.githubusercontent.com/35893306/53339359-6fcfff00-3906-11e9-9d99-c2d2ded9b509.png)

**Comment by ildyria** [comment]
Can you have a look at the takedate of the pictures inside the albums?

**Comment by SerenaButler** [comment]
Take (Captured?) Date seems fine, but Uploaded date is "wrong".

![image](https://user-images.githubusercontent.com/35893306/53341450-e0c5e580-390b-11e9-89f8-e26b46c09005.png)

**Comment by SerenaButler** [comment]
Lychee 3 and 4 DB Album Table

![image](https://user-images.githubusercontent.com/35893306/53341950-29ca6980-390d-11e9-98cb-59b18289dcf4.png)

**Comment by ildyria** [comment]
Gotcha.
We just need to add
```php
Album::reset_takestamp()
```
in https://github.com/LycheeOrg/Lychee-Laravel/blob/master/database/migrations/2018_08_15_103716_move_photos.php

**Comment by SerenaButler** [comment]
I'm not sure if this is related but Album sort with new creates Albums does not work as expected.

Setting is: "Sort albums by Creation Time in an Ascending order"  So the bot Albums created today should not be the first two ones.

![image](https://user-images.githubusercontent.com/35893306/53814008-1f3c4f80-3f5f-11e9-8c29-633a95f1b647.png)

**Comment by d7415** [comment]
> I'm not sure if this is related but Album sort with new creates Albums does not work as expected.
> 
> Setting is: "Sort albums by Creation Time in an Ascending order" So the bot Albums created today should not be the first two ones.
> 
> ![image](https://user-images.githubusercontent.com/35893306/53814008-1f3c4f80-3f5f-11e9-8c29-633a95f1b647.png)

Note to add that this is now #123.
