### ISSUE TITLE
Feature proposal: better support for movies

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#93]
I can't believe I'm suggesting this since I generally hate taking movies, but...

The current support is minimal at best. Only the square thumbnails are generated; why not at least the small variant as well? No useful metadata is extracted (at least things like width/height/fps/duration would be helpful).

I'll be happy to give it a shot next, once HiDPI is in.

For metadata, should I extend the `photos` table or should I simply overload some of the existing fields to avoid a need for database migration?

**Comment by ildyria** [comment]
> For metadata, should I extend the `photos` table or should I simply overload some of the existing fields to avoid a need for database migration?

I think you can overload. The `type` is the part making the difference.

**Comment by kamil4** [comment]
Thanks for the reminder! This one's finished; closing.
