### ISSUE TITLE
Feature proposal: fullscreen button

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#94]
I know I can hit F12 to switch my desktop browser to full screen mode but I think some people would appreciate a "full screen" button on the screen that does that. Many galleries seem to have it. What would you say about adding one to the frontend?

**Comment by ildyria** [comment]
Isn't it F11 ? :smile: 

If you want to give it a shot sure. I don't really see it a priority but I don't have anything against.
However if you do it, please add a keybind for it to `F` (Lightroom keybinding :wink: )

**Comment by kamil4** [comment]
LOL, clearly I've been hitting that F12 too much lately, it got etched on my brain :wink:

Sure, I absolutely agree that it's low priority. Clearly I'm reaching the bottom of my personal TODO list if I mention such things :smiley:

**Comment by ildyria** [comment]
Well, there are some bugs left that are higher in the list, such as : 
https://github.com/LycheeOrg/Lychee-Laravel/issues/91
https://github.com/LycheeOrg/Lychee-Laravel/issues/88
https://github.com/LycheeOrg/Lychee-Laravel/issues/58
https://github.com/LycheeOrg/Lychee-Laravel/issues/48 < This one would be very nice. :)

**Comment by ildyria** [comment]
done.
