### ISSUE TITLE
Download not working, resulting in 404

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#97]
Download not working, resulting in 404.

![image](https://user-images.githubusercontent.com/35893306/53585843-2cd08e80-3b87-11e9-8fba-0a8d1171bf94.png)

**Comment by ildyria** [comment]
Yeah, I never bothered to implement this as usually i just right click on the picture.
I would say bother @guzzisti if you want this functionality. :smile:

**Comment by SerenaButler** [comment]
Hahahaha ....I justed checked because downloading medium and small size are "new" and it worked in Lychee 3 though :-)

**Comment by kamil4** [comment]
It amazes me that server support is needed for downloading, given that we can obviously access those images from the frontend for rendering. But I guess that's how HTTP works? :astonished:

**Comment by ildyria** [comment]
@kamil4 no. It's just that the front end uses the server API even for simple things like that.

**Comment by kamil4** [comment]
@ildyria I don't mean to put you on the spot here, but *should* the front end do it that way? Could you or @d7415 make an "executive decision" about this? :smiley: 
I mean, if we can achieve this purely in the front end, without having to mess with the server, then why are we complicating our lives like that? I did some preliminary reading and apparently we could use HTML5 "download" attribute for such things. Is that the way to go?
Come to think of it, I don't actually know what the expected minimum browser requirements are for Lychee; I assume HTML5 is fine? We use `video` and `srcset`, which are HTML5...

**Comment by d7415** [comment]
I mostly agree. As far as I can tell the reason is that the back end (of v3) changes the headers to "force" the download.

As to HTML 5, I don't think all directives are equal. `video` should be fine, and I'm pretty sure `srcset` fails gracefully. I would think download should be fine, but haven't looked in any detail.

But yes, I think I implied my preference for sticking to front where we can in the download medium/small PR.

**Comment by guzzisti** [comment]
I today came across that in Lychee V3, the Frontend behaves inconsistently. The downloads are handled by the backend using the API, the "full photo" function is a frontend-only implementation which redirects to the physical file.

From my understanding, if you want to enforce user permissions (which you should in a multi-user application), you have to do that in the backend. A frontend only implementation could be bypassed rather easily.

**Comment by kamil4** [comment]
All the image rendering works by the backend sending the frontend URLs to the image files (or was there a plugin in v3 to do it differently?). That's clearly not secure (there's no way to prevent the sharing of URLs outside of Lychee), although at least the names of the files are not easily guessable.
Personally I don't have a use case that would require to keep individual image files inaccessible outside of Lychee, but if somebody decides to make it secure, I would think they'll have their work cut out for them, judging by what I've seen in the code of the front end.

**Comment by d7415** [comment]
The webroot plugin for v3 makes all.requests for files go through Lychee's auth code. If you have access it serves the file, if you don't it doesn't. Requires a little extra server configuration (and maybe some tweaks for recent Lychee? I forget) but seems to work.
